#!/usr/bin/env python3
r"""
==============================================================================
Run03: Extract Cell-Specific DeepTAN Network
==============================================================================

Purpose
-------
Extract a cell-specific latent gene network from a cell-type fine-tuned DeepTAN
model.

Pipeline position
-----------------
Run01: user-defined scRNA files -> LitData
Run02: LitData -> cell-type fine-tuned DeepTAN checkpoint
Run03: LitData + fine-tuned checkpoint -> cell-specific latent network

Core computation
----------------
This script keeps the original CSN extraction logic:

  1. Load the scRNA-pretrained DeepTAN model.
  2. Dynamically import the Run02 fine-tuning LightningModule class.
  3. Load the fine-tuned checkpoint.
  4. Extract node embeddings from all LitData splits: trn + val + tst.
  5. Aggregate gene embeddings across cells.
  6. Compute cosine-similarity edge weights:
       w_ij = cos_sim(mean_h_i, mean_h_j)
  7. Compute cell-specific change:
       delta_w_ij = w_ij(fine-tuned) - w_ij(pretrained)
  8. Save the full edge table, gene embeddings, cell embeddings and metadata.

The complete edge table is saved without downstream filtering. Edge filtering,
module detection and hub analysis should be performed in later downstream scripts.

Recommended single-run usage
----------------------------
python run_03_extract_cell_network_userfriendly.py \
    --config cell_network_single.yaml

Optional overrides
------------------
python run_03_extract_cell_network_userfriendly.py \
    --config cell_network_single.yaml \
    --litdata_dir /path/to/cell_litdata \
    --finetuned_ckpt /path/to/best_model.ckpt \
    --output_dir /path/to/cell_network_output

Notes for GitHub users
----------------------
The main user-facing workflow is single-run:

  litdata_dir       : output directory generated by Run01
  finetuned_ckpt    : checkpoint generated by Run02
  output_dir        : directory where Run03 outputs will be written

The legacy multi-cell-group configuration style is still supported for internal
batch experiments, but it is not required for the standard workflow.

Author: DeepTAN Cell-Specific Network Extraction Pipeline
"""

import argparse
import copy
import hashlib
import importlib
import inspect
import os
import pickle
import sys
import time
import warnings
from typing import Any, Dict, List, Optional, Set, Tuple

import numpy as np
import polars as pl
import torch
import torch.nn as nn
import torch.nn.functional as F
import yaml
from loguru import logger
from torch_geometric.data import Data as GData
from torch_geometric.utils import subgraph as pyg_subgraph

warnings.filterwarnings("ignore", category=FutureWarning)

# ── Optional local DeepTAN source checkout ───────────────────────────────────
# Set DEEPTAN_SRC in the shell script when DeepTAN is not installed as a package.
# Example:
#   export DEEPTAN_SRC="/path/to/deeptan-dev/src"
_LOCAL_DEEPTAN = os.environ.get("DEEPTAN_SRC", "").strip()
if _LOCAL_DEEPTAN and _LOCAL_DEEPTAN not in sys.path:
    sys.path.insert(0, _LOCAL_DEEPTAN)

# ── Optional default directory containing the Run02 fine-tuning module ───────
# This can also be provided in config.finetune_module_dir.
_DEFAULT_FINETUNE_MODULE_DIR = os.environ.get("FINETUNE_MODULE_DIR", "").strip()
if _DEFAULT_FINETUNE_MODULE_DIR and _DEFAULT_FINETUNE_MODULE_DIR not in sys.path:
    sys.path.insert(0, _DEFAULT_FINETUNE_MODULE_DIR)

import deeptan.constants as const
from deeptan.graph.model import DeepTAN
from deeptan.utils.data import DeepTANDataModuleLit
from deeptan.utils.uni import get_map_location


# ============================================================================
# 0. Configuration
# ============================================================================

DEFAULT_CSN_CONFIG = {
    # ------------------------------------------------------------------
    # Single-run user-facing configuration
    # ------------------------------------------------------------------
    # These fields are sufficient for the standard GitHub workflow.
    "pretrained_ckpt": "",
    "cell_group_name": "ExampleCellType",
    "litdata_dir": "",
    "finetuned_ckpt": "",
    "split_id": None,

    # Save outputs directly under output_dir/csn when True.
    # Legacy batch mode keeps output_dir/<cell_group>/<split>/csn.
    "simple_output": False,

    # ------------------------------------------------------------------
    # Legacy / advanced multi-cell-group configuration
    # ------------------------------------------------------------------
    "finetune_output_dir": "",
    "pretrained_labels_parquet": "",
    "cell_groups": {},
    "cell_group_order": [],

    # ------------------------------------------------------------------
    # Fine-tuning module import
    # ------------------------------------------------------------------
    # finetune_module_dir should point to the directory containing the Run02
    # fine-tuning script. finetune_module_name is the Python module name
    # without .py.
    "finetune_module_dir": "",
    "finetune_module_name": "run_02_cell_finetune_userfriendly",
    "finetune_class_name": "DeepTANFineTune",

    # ------------------------------------------------------------------
    # Output and hardware
    # ------------------------------------------------------------------
    "output_dir": "output/cell_network",
    "accelerator": "auto",
    "devices": 1,
    "precision": "32-true",
    "batch_size": 32,
    "n_workers": 4,
}


def load_csn_config(config_path: Optional[str] = None) -> Dict[str, Any]:
    """Load and merge CSN configuration."""
    config = copy.deepcopy(DEFAULT_CSN_CONFIG)
    if config_path and os.path.exists(config_path):
        with open(config_path, "r") as f:
            user_cfg = yaml.safe_load(f) or {}
        for k, v in user_cfg.items():
            if isinstance(v, dict) and isinstance(config.get(k), dict):
                config[k].update(v)
            else:
                config[k] = v
        logger.info(f"Loaded CSN config from {config_path}")
    return config


# ============================================================================
# 1. Utility functions
# ============================================================================

def _param_hash(module: nn.Module) -> str:
    """Compute an MD5 hash of module parameters for weight-change verification."""
    h = hashlib.md5()
    for p in module.parameters():
        h.update(p.detach().cpu().numpy().tobytes())
    return h.hexdigest()[:16]


def _verify_gat_weights_differ(
    pre_layers: nn.Module,
    ft_layers: nn.Module,
    label: str = "",
) -> bool:
    """Verify that the fine-tuned GAT weights differ from the pretrained GAT weights.

Returns True when the weights differ, which is the expected condition after successful fine-tuning. Returns False when the weights are identical."""
    pre_hash = _param_hash(pre_layers)
    ft_hash = _param_hash(ft_layers)
    if pre_hash == ft_hash:
        logger.error(
            f"  ✗ GAT weights IDENTICAL between pretrained and fine-tuned! {label}\n"
            f"    pre_hash={pre_hash}, ft_hash={ft_hash}\n"
            f"    Possible cause: checkpoint loading failed or the checkpoint path is incorrect."
        )
        return False
    logger.success(
        f"  ✓ GAT weights verified different. {label}\n"
        f"    pre_hash={pre_hash}, ft_hash={ft_hash}"
    )
    return True


# ============================================================================
# 2. Model loading
# ============================================================================

def load_pretrained_for_extraction(
    ckpt_path: str,
    map_location: str = "cpu",
) -> DeepTAN:
    """Load the scRNA-pretrained DeepTAN model for network extraction."""
    model_dir = os.path.dirname(ckpt_path)
    hparams_path = os.path.join(model_dir, "version_0", "hparams.yaml")
    load_kwargs = {"map_location": map_location}
    if os.path.exists(hparams_path):
        load_kwargs["hparams_file"] = hparams_path
    model = DeepTAN.load_from_checkpoint(ckpt_path, **load_kwargs)
    model.eval()
    logger.info(f"Loaded pretrained model: {ckpt_path}")
    logger.info(
        f"  nodes={model.num_all_nodes}, "
        f"label_dim={model.output_g_label_dim}, "
        f"is_regression={model.is_regression}"
    )
    return model


def _resolve_finetune_class(config: Dict[str, Any]):
    """Dynamically import the cell fine-tuning LightningModule class."""
    module_dir = config.get("finetune_module_dir", _DEFAULT_FINETUNE_MODULE_DIR)
    module_name = config.get("finetune_module_name", "csn_finetune")
    class_name = config.get("finetune_class_name", "DeepTANFineTune")

    if module_dir and module_dir not in sys.path:
        sys.path.insert(0, module_dir)

    module = importlib.import_module(module_name)
    if not hasattr(module, class_name):
        raise AttributeError(
            f"Cannot find class '{class_name}' in module '{module_name}'. "
            f"Check finetune_module_dir/module_name/class_name in config."
        )
    return getattr(module, class_name)


def _instantiate_finetune_module(
    finetune_cls,
    pretrained_model: DeepTAN,
    ft_config: Dict[str, Any],
    group_num_classes: int,
) -> nn.Module:
    """Instantiate the cell fine-tuning module while adapting to compatible constructor signatures."""
    sig = inspect.signature(finetune_cls.__init__)
    params = set(sig.parameters.keys())

    kwargs = {
        "pretrained_model": copy.deepcopy(pretrained_model),
        "cv_weights": torch.ones(len(pretrained_model.dict_node_names)),
        "class_weights": None,
        "config": ft_config,
    }

    num_class_aliases = [
        "group_num_classes",
        "cell_group_num_classes",
        "cell_num_classes",
        "celltype_num_classes",
        "tissue_num_classes",
        "num_classes",
        "output_g_label_dim",
    ]
    for key in num_class_aliases:
        if key in params:
            kwargs[key] = group_num_classes
            break

    try:
        return finetune_cls(**kwargs)
    except TypeError as e:
        raise TypeError(
            "Failed to instantiate fine-tune module. "
            f"Tried kwargs keys={sorted(kwargs.keys())}. "
            "Check the constructor signature in csn_finetune.py."
        ) from e


def load_finetuned_for_extraction(
    pretrained_model: DeepTAN,
    ft_ckpt_path: str,
    litdata_dir: str,
    config: Dict[str, Any],
    finetune_log_dir: Optional[str] = None,
    map_location: str = "cpu",
) -> nn.Module:
    """Load the cell-type fine-tuned model for network extraction.

The loader first tries to recover the actual training configuration from finetune_metadata.pkl, then from checkpoint hyper_parameters. If neither source is available, safe inference defaults are used."""
    finetune_cls = _resolve_finetune_class(config)

    # ── Read LitData metadata ────────────────────────────────────────
    pkl_path = os.path.join(litdata_dir, const.fname.litdata_others2save_pkl)
    with open(pkl_path, "rb") as f:
        others = pickle.load(f)
    group_num_classes = others["output_g_label_dim"]

    ft_config = None

    if finetune_log_dir:
        meta_path = os.path.join(finetune_log_dir, "finetune_metadata.pkl")
        if os.path.exists(meta_path):
            with open(meta_path, "rb") as f:
                meta = pickle.load(f)
            ft_config = meta.get("config")
            if ft_config:
                logger.info("  [BUG-1] Loaded training config from finetune_metadata.pkl")

    if ft_config is None:
        ckpt_dir = os.path.dirname(ft_ckpt_path)
        meta_path = os.path.join(ckpt_dir, "finetune_metadata.pkl")
        if os.path.exists(meta_path):
            with open(meta_path, "rb") as f:
                meta = pickle.load(f)
            ft_config = meta.get("config")
            if ft_config:
                logger.info(f"  [BUG-1] Loaded training config from {meta_path}")

    if ft_config is None:
        ckpt_data = torch.load(ft_ckpt_path, map_location="cpu")
        hp = ckpt_data.get("hyper_parameters", {})
        if "config" in hp:
            ft_config = hp["config"]
            logger.info("  [BUG-1] Loaded config from checkpoint hyper_parameters")

    if ft_config is None:
        logger.warning(
            "  [BUG-1] Cannot find training config. Using safe defaults.\n"
            "  This may cause minor inconsistencies in buffer initialization,\n"
            "  but will NOT affect inference results (forward pass is config-independent)."
        )
        ft_config = {
            "base_lr": 3e-5,
            "lr_multipliers": {
                "embed": 0.0, "feature_proj": 0.1, "fusion_mlp": 0.1,
                "gat_layers": 0.2, "pooling": 0.2,
                "ge_decoder": 0.3, "g_label_predictor": 1.0,
            },
            "weight_decay": 1e-5, "warmup_epochs": 3,
            "loss_zero_coeff": 0.5, "lambda_anchor": 0.02,
            "focal_gamma": 2.0,
            "scheduler": "cosine_warm_restarts",
            "cosine_T0": 9, "cosine_T_mult": 1,
            "plateau_patience": 5, "plateau_factor": 0.5,
            "min_lr": 1e-7, "max_epochs": 50,
        }

    ft_module = _instantiate_finetune_module(
        finetune_cls=finetune_cls,
        pretrained_model=pretrained_model,
        ft_config=ft_config,
        group_num_classes=group_num_classes,
    )

    ckpt = torch.load(ft_ckpt_path, map_location=map_location)
    state_dict = ckpt["state_dict"] if "state_dict" in ckpt else ckpt

    missing, unexpected = ft_module.load_state_dict(state_dict, strict=False)
    if missing:
        real_missing = [k for k in missing if not k.startswith("_anchor_")]
        if real_missing:
            logger.warning(f"  Missing keys (non-anchor): {real_missing[:5]}...")
    if unexpected:
        logger.warning(f"  Unexpected keys: {unexpected[:5]}...")

    ft_module.eval()
    logger.info(f"Loaded fine-tuned model: {ft_ckpt_path}")
    logger.info(f"  finetune_module={finetune_cls.__module__}.{finetune_cls.__name__}")
    logger.info(f"  group_num_classes={group_num_classes}")
    return ft_module


# ============================================================================
# 3. Core signal extraction
# ============================================================================

def _extract_node_embeddings(
    model_amsgp: nn.Module,
    batch: GData,
    dict_node_names: Dict[str, int],
    device: torch.device = torch.device("cpu"),
) -> Dict[str, Any]:
    """Extract node embeddings from the AMSGP NodeEmbedding stack.

The original forward method is not modified. This function calls the relevant submodules directly and returns per-graph node embeddings, gene IDs, local edge indices, and node names."""
    node_embedding_layers = model_amsgp.node_embedding_layers

    # ── Parse the batch structure ─────────────────────────────────────
    node_batch = getattr(
        batch, "batch",
        torch.zeros(batch.x.size(0), dtype=torch.long, device=device),
    )
    x = batch.x.float().to(device)
    edge_index = batch.edge_index.long().to(device)
    node_batch = node_batch.to(device)

    unique_batches, inverse, counts = torch.unique(
        node_batch, return_inverse=True, return_counts=True
    )
    node_indices_list = torch.split(
        torch.arange(node_batch.size(0), device=device), counts.tolist()
    )

    # ── Parse node_names ───────────────────────────────────────────────
    node_names = batch.node_names
    if isinstance(node_names[0], list):
        node_names_flat = [n for sublist in node_names for n in sublist]
    else:
        node_names_flat = list(node_names)

    node_names_splits = []
    start_idx = 0
    for count in counts.tolist():
        node_names_splits.append(node_names_flat[start_idx:start_idx + count])
        start_idx += count

    # ── Extract embeddings graph by graph ─────────────────────────────
    results = {
        "node_embeddings": [],
        "node_gene_ids": [],
        "edge_indices_local": [],
        "node_names_per_graph": [],
    }

    for i, (node_indices, graph_node_names) in enumerate(
        zip(node_indices_list, node_names_splits)
    ):
        if node_indices.numel() == 0:
            continue

        sub_x = x[node_indices]
        sub_edge_index, _ = pyg_subgraph(
            node_indices, edge_index,
            relabel_nodes=True, num_nodes=x.size(0),
        )
        if sub_edge_index.numel() == 0:
            continue

        # ── Manually run the NodeEmbedding forward path ───────────────────
        # Filter unknown gene names to avoid KeyError
        valid_mask = [n in dict_node_names for n in graph_node_names]
        if not all(valid_mask):
            n_invalid = sum(1 for v in valid_mask if not v)
            if n_invalid > len(graph_node_names) * 0.5:
                continue  # More than half of the gene names are invalid; skip this graph
            # Keep only valid genes in this rare case
            valid_indices = [j for j, v in enumerate(valid_mask) if v]
            graph_node_names = [graph_node_names[j] for j in valid_indices]
            sub_x = sub_x[valid_indices]
            # Rebuilding edge_index is non-trivial here; skip this graph for safety
            continue

        ids = torch.tensor(
            [dict_node_names[n] for n in graph_node_names], device=device
        )
        node_embs = node_embedding_layers.embed(ids)
        x_proj = node_embedding_layers.feature_proj(sub_x.unsqueeze(-1)).squeeze(1)
        fused = torch.cat([node_embs, x_proj], dim=-1)
        fused = node_embedding_layers.fusion_mlp(fused)

        # ── Run GAT layers normally without extracting attention weights ──
        for layer in node_embedding_layers._layers:
            fused = layer(fused, sub_edge_index)

        fused = node_embedding_layers.norm(fused)

        results["node_embeddings"].append(fused.detach().cpu())
        results["node_gene_ids"].append(ids.detach().cpu())
        results["edge_indices_local"].append(sub_edge_index.detach().cpu())
        results["node_names_per_graph"].append(list(graph_node_names))

    return results


@torch.no_grad()
def extract_signals_from_dataloader(
    model: nn.Module,
    dataloaders: List,
    dict_node_names: Dict[str, int],
    device: torch.device = torch.device("cpu"),
    max_batches: Optional[int] = None,
) -> Tuple[Dict[int, List[np.ndarray]], Set[Tuple[int, int]], List[np.ndarray]]:
    """Iterate over multiple dataloaders and collect gene embeddings, edge pairs, and cell embeddings.

All train, validation, and test dataloaders can be traversed to maximize gene coverage during network extraction."""
    if hasattr(model, "amsgp"):
        amsgp = model.amsgp
    else:
        raise ValueError("Model does not have 'amsgp' attribute")

    model.eval()
    amsgp.eval()

    gene_embeddings_all: Dict[int, List[np.ndarray]] = {}
    edge_pairs_all: Set[Tuple[int, int]] = set()
    cell_embeddings_all: List[np.ndarray] = []  # [NEW] cell embedding list
    n_cells = 0
    n_batches_total = 0
    t_start = time.time()

    for loader_idx, dataloader in enumerate(dataloaders):
        loader_name = ["train", "val", "test"][loader_idx] if loader_idx < 3 else f"loader_{loader_idx}"
        n_cells_loader = 0

        for batch_idx, batch in enumerate(dataloader):
            if max_batches and n_batches_total >= max_batches:
                break

            batch = batch.to(device)

            try:
                signals = _extract_node_embeddings(
                    amsgp, batch, dict_node_names, device=device,
                )
            except Exception as e:
                logger.warning(f"  Batch {n_batches_total} extraction failed: {e}")
                continue

            # ── Collect signals for each graph / cell ─────────────────────────
            for gi in range(len(signals["node_embeddings"])):
                embs = signals["node_embeddings"][gi].numpy()
                gene_ids = signals["node_gene_ids"][gi].numpy()
                edge_index_local = signals["edge_indices_local"][gi].numpy()

                # [NEW] Cell embedding: mean pooling across all gene embeddings in this cell
                cell_emb = embs.mean(axis=0)
                cell_embeddings_all.append(cell_emb)

                # Gene embeddings; original logic is unchanged
                for ni in range(len(gene_ids)):
                    gid = int(gene_ids[ni])
                    if gid not in gene_embeddings_all:
                        gene_embeddings_all[gid] = []
                    gene_embeddings_all[gid].append(embs[ni])

                # Edge set collected from the original edge_index and canonicalized as undirected
                n_local_nodes = len(gene_ids)
                for ei in range(edge_index_local.shape[1]):
                    local_src = int(edge_index_local[0, ei])
                    local_dst = int(edge_index_local[1, ei])

                    # Boundary check
                    if local_src >= n_local_nodes or local_dst >= n_local_nodes:
                        continue

                    gsrc = int(gene_ids[local_src])
                    gdst = int(gene_ids[local_dst])

                    # Remove self-loops
                    if gsrc == gdst:
                        continue

                    # Canonical undirected storage: always store (min_id, max_id)
                    edge_pair = (min(gsrc, gdst), max(gsrc, gdst))
                    edge_pairs_all.add(edge_pair)

                n_cells += 1
                n_cells_loader += 1

            n_batches_total += 1
            if n_batches_total % 20 == 0:
                elapsed = time.time() - t_start
                logger.info(
                    f"    [{n_batches_total} batches, {n_cells} cells, "
                    f"{len(gene_embeddings_all)} genes, "
                    f"{len(edge_pairs_all)} edges, "
                    f"{elapsed:.1f}s]"
                )

        logger.info(f"    {loader_name}: {n_cells_loader} cells")

    elapsed = time.time() - t_start
    logger.info(
        f"  Extraction complete: {n_cells} cells (all splits), "
        f"{len(gene_embeddings_all)} genes, "
        f"{len(edge_pairs_all)} edges, "
        f"{len(cell_embeddings_all)} cell embeddings "
        f"({elapsed:.1f}s)"
    )

    return gene_embeddings_all, edge_pairs_all, cell_embeddings_all


# ============================================================================
# 4. Signal aggregation and edge-weight calculation
# ============================================================================

def aggregate_signals(
    gene_embeddings_all: Dict[int, List[np.ndarray]],
    edge_pairs: Set[Tuple[int, int]],
    gene_id_to_name: Dict[int, str],
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Aggregate gene embeddings across cells and compute cosine-similarity edge weights.

The edge weight is defined as w_ij = cos_sim(mean_h_i, mean_h_j) on observed undirected edges."""
    # ── Mean gene embeddings ──────────────────────────────────────────
    if not gene_embeddings_all:
        logger.error("  No gene embeddings collected!")
        return np.array([]), np.array([]), np.array([])

    n_genes = max(gene_embeddings_all.keys()) + 1
    hidden_dim = 0
    for v in gene_embeddings_all.values():
        if v:
            hidden_dim = v[0].shape[0]
            break

    mean_embeddings = np.zeros((n_genes, hidden_dim), dtype=np.float32)
    gene_cell_counts = np.zeros(n_genes, dtype=np.int64)

    for gid, emb_list in gene_embeddings_all.items():
        stacked = np.stack(emb_list, axis=0)
        mean_embeddings[gid] = stacked.mean(axis=0)
        gene_cell_counts[gid] = len(emb_list)

    n_genes_observed = int((gene_cell_counts > 0).sum())
    logger.info(
        f"  Gene embeddings: {n_genes_observed}/{n_genes} genes observed, "
        f"dim={hidden_dim}"
    )

    # ── Compute cosine similarity on observed edges only ──────────────
    edge_list = sorted(edge_pairs)  # deterministic output order

    if not edge_list:
        logger.error("  No edges found!")
        return mean_embeddings, np.array([]), np.array([])

    edge_array = np.array(edge_list, dtype=np.int64)
    cos_sim = np.zeros(len(edge_array), dtype=np.float64)

    for ei in range(len(edge_array)):
        gi, gj = edge_array[ei]
        ei_emb = mean_embeddings[gi]
        ej_emb = mean_embeddings[gj]
        norm_i = np.linalg.norm(ei_emb)
        norm_j = np.linalg.norm(ej_emb)
        if norm_i > 1e-8 and norm_j > 1e-8:
            cos_sim[ei] = float(np.dot(ei_emb, ej_emb) / (norm_i * norm_j))

    # ── Distribution diagnostics ──────────────────────────────────────
    logger.info(f"  Edges: {len(edge_array)}")
    n_neg_sim = int((cos_sim < 0).sum())
    n_pos_sim = int((cos_sim > 0).sum())
    logger.info(
        f"  Cosine sim (= edge weight w) stats: "
        f"min={cos_sim.min():.4f}, max={cos_sim.max():.4f}, "
        f"mean={cos_sim.mean():.4f}, std={cos_sim.std():.4f}, "
        f"positive={n_pos_sim} ({n_pos_sim / len(cos_sim):.1%}), "
        f"negative={n_neg_sim} ({n_neg_sim / len(cos_sim):.1%})"
    )

    return mean_embeddings, edge_array, cos_sim


def compute_delta(
    w_pre: np.ndarray,
    edge_array_pre: np.ndarray,
    w_ft: np.ndarray,
    edge_array_ft: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Compute delta_w = w_ft - w_pre on the common edge set only."""
    pre_dict = {
        (int(edge_array_pre[i, 0]), int(edge_array_pre[i, 1])): float(w_pre[i])
        for i in range(len(edge_array_pre))
    }
    ft_dict = {
        (int(edge_array_ft[i, 0]), int(edge_array_ft[i, 1])): float(w_ft[i])
        for i in range(len(edge_array_ft))
    }

    common_keys = sorted(set(pre_dict.keys()) & set(ft_dict.keys()))
    if not common_keys:
        logger.error("  No common edges between pretrained and fine-tuned!")
        return np.array([]), np.array([]), np.array([]), np.array([])

    common_edges = np.array(common_keys, dtype=np.int64)
    w_pre_aligned = np.array([pre_dict[k] for k in common_keys], dtype=np.float64)
    w_ft_aligned = np.array([ft_dict[k] for k in common_keys], dtype=np.float64)
    delta_w = w_ft_aligned - w_pre_aligned

    logger.info(
        f"  Common edges: {len(common_keys)} "
        f"(pre_only={len(pre_dict) - len(common_keys)}, "
        f"ft_only={len(ft_dict) - len(common_keys)})"
    )
    logger.info(
        f"  Δw: mean={delta_w.mean():.6f}, std={delta_w.std():.6f}, "
        f"median={np.median(delta_w):.6f}"
    )
    logger.info(
        f"    positive: {(delta_w > 0).sum()} ({(delta_w > 0).sum() / len(delta_w):.1%}), "
        f"negative: {(delta_w < 0).sum()} ({(delta_w < 0).sum() / len(delta_w):.1%})"
    )

    return common_edges, delta_w, w_pre_aligned, w_ft_aligned


# ============================================================================
# 5. Network construction and output writing
# ============================================================================

def build_network(
    common_edges: np.ndarray,
    delta_w: np.ndarray,
    w_pre: np.ndarray,
    w_ft: np.ndarray,
    gene_id_to_name: Dict[int, str],
) -> Dict[str, Any]:
    """Build the complete cell-group-specific weighted network without downstream filtering.

Filtering, module detection, and hub analysis are intentionally left to downstream scripts."""
    n_edges = len(delta_w)

    # ── Complete edge table ───────────────────────────────────────────
    edge_table_rows = []
    for ei in range(n_edges):
        gi = int(common_edges[ei, 0])
        gj = int(common_edges[ei, 1])
        edge_table_rows.append({
            "gene_i_id": gi,
            "gene_j_id": gj,
            "gene_i_name": gene_id_to_name.get(gi, f"gene_{gi}"),
            "gene_j_name": gene_id_to_name.get(gj, f"gene_{gj}"),
            "w_pre": round(float(w_pre[ei]), 8),
            "w_ft": round(float(w_ft[ei]), 8),
            "delta_w": round(float(delta_w[ei]), 8),
        })

    result = {
        "edge_table": edge_table_rows,
        "n_total_edges": n_edges,
    }

    logger.info(f"  Network built: {n_edges} total edges")
    logger.info(
        f"    Δw range: [{delta_w.min():.6f}, {delta_w.max():.6f}]"
    )

    return result


def save_csn_output(
    output_dir: str,
    cell_group_name: str,
    split_id: Optional[str],
    network: Dict[str, Any],
    mean_embeddings_pre: np.ndarray,
    mean_embeddings_ft: np.ndarray,
    gene_id_to_name: Dict[int, str],
    config: Dict[str, Any],
    raw_signals: Optional[Dict] = None,
    extra_stats: Optional[Dict] = None,
    cell_embeddings_ft: Optional[np.ndarray] = None,
) -> str:
    """Save CSN edge tables, embeddings, raw signals, and metadata."""
    if bool(config.get("simple_output", False)):
        # User-facing single-run mode:
        #   output_dir/csn/
        out_dir = os.path.join(output_dir, "csn")
    elif split_id:
        # Legacy batch mode:
        #   output_dir/<cell_group>/<split>/csn/
        out_dir = os.path.join(output_dir, cell_group_name, split_id, "csn")
    else:
        # Legacy single-cell-group mode:
        #   output_dir/<cell_group>/csn/
        out_dir = os.path.join(output_dir, cell_group_name, "csn")
    os.makedirs(out_dir, exist_ok=True)

    display_name = f"{cell_group_name}/{split_id}" if split_id else cell_group_name

    # 1. Complete edge table (parquet)
    edge_df = pl.DataFrame(network["edge_table"])
    edge_df.write_parquet(os.path.join(out_dir, "csn_edge_table.parquet"))

    # 2. Gene embedding matrices
    np.save(
        os.path.join(out_dir, "mean_embeddings_pretrained.npy"),
        mean_embeddings_pre,
    )
    np.save(
        os.path.join(out_dir, "mean_embeddings_finetuned.npy"),
        mean_embeddings_ft,
    )

    # 3. [NEW] Cell embedding matrix from the fine-tuned model for UMAP visualization
    if cell_embeddings_ft is not None and len(cell_embeddings_ft) > 0:
        np.save(
            os.path.join(out_dir, "cell_embeddings_finetuned.npy"),
            cell_embeddings_ft,
        )
        logger.info(
            f"  Saved cell embeddings: {cell_embeddings_ft.shape[0]} cells, "
            f"dim={cell_embeddings_ft.shape[1]}"
        )

    # 4. Gene-name mapping
    gene_map_rows = [
        {"gene_id": gid, "gene_name": gname}
        for gid, gname in sorted(gene_id_to_name.items())
    ]
    pl.DataFrame(gene_map_rows).write_csv(
        os.path.join(out_dir, "gene_id_map.csv")
    )

    # 5. Raw signals for diagnostics and reanalysis
    if raw_signals:
        raw_dir = os.path.join(out_dir, "raw_signals")
        os.makedirs(raw_dir, exist_ok=True)
        for key, val in raw_signals.items():
            if isinstance(val, np.ndarray):
                np.save(os.path.join(raw_dir, f"{key}.npy"), val)

    # 6. Metadata
    metadata = {
        "cell_group_name": cell_group_name,
        "split_id": split_id,
        "n_total_edges": network["n_total_edges"],
        "n_genes": len(gene_id_to_name),
        "n_cells": int(cell_embeddings_ft.shape[0]) if cell_embeddings_ft is not None else 0,
        "edge_weight_method": "cosine_similarity",
        "data_scope": "all (train + val + test)",
        "entity_type": "cell_group",
        "extra_stats": extra_stats or {},
    }
    with open(os.path.join(out_dir, "csn_metadata.yaml"), "w") as f:
        yaml.dump(metadata, f, default_flow_style=False, allow_unicode=True)

    # ── Summary log ───────────────────────────────────────────────────
    logger.info(f"\n  {'─' * 50}")
    logger.info(f"  CSN Output: {display_name}")
    logger.info(f"  Directory: {out_dir}")
    logger.info(f"  {'─' * 50}")
    total_kb = 0
    for item in sorted(os.listdir(out_dir)):
        item_path = os.path.join(out_dir, item)
        if os.path.isfile(item_path):
            sz = os.path.getsize(item_path) / 1024
            total_kb += sz
            logger.info(f"    {item} ({sz:.1f} KB)")
    logger.info(f"    Total: {total_kb:.1f} KB")

    return out_dir


# ============================================================================
# 6. Single-cell-group processing pipeline
# ============================================================================

def process_single_cell_group(
    cell_group_name: str,
    split_id: Optional[str],
    pretrained_model: DeepTAN,
    ft_ckpt_path: str,
    litdata_dir: str,
    config: Dict[str, Any],
    device: torch.device,
) -> Optional[str]:
    """Run the complete CSN extraction workflow for one cell group and optional split."""
    display_name = f"{cell_group_name}/{split_id}" if split_id else cell_group_name

    logger.info(f"\n{'=' * 70}")
    logger.info(f"  CSN EXTRACTION: {display_name}")
    logger.info(f"  Checkpoint: {ft_ckpt_path}")
    logger.info(f"  LitData: {litdata_dir}")
    logger.info(f"{'=' * 70}")

    # ── Data loading: use all splits, train + val + test ──────────────
    dm = DeepTANDataModuleLit(
        litdata_dir,
        batch_size=config["batch_size"],
        n_workers=config["n_workers"],
    )
    dm.setup()
    all_dataloaders = [
        dm.train_dataloader(),
        dm.val_dataloader(),
        dm.test_dataloader(),
    ]
    logger.info(f"  Data: using ALL splits (train + val + test)")

    dict_node_names = pretrained_model.dict_node_names
    gene_id_to_name = {v: k for k, v in dict_node_names.items()}

    # ── Infer finetune_log_dir for metadata loading ───────────────────
    finetune_log_dir = os.path.dirname(ft_ckpt_path)

    # ── Step 1a: extract signals from the pretrained model ────────────
    logger.info(f"\n  [Step 1a] Extracting embeddings from PRETRAINED model ...")
    pre_model = copy.deepcopy(pretrained_model).to(device)
    pre_model.eval()

    gene_emb_pre, edge_pairs_pre, _ = extract_signals_from_dataloader(
        pre_model, all_dataloaders, dict_node_names, device=device,
    )
    # Pretrained cell embeddings are not saved here; UMAP uses fine-tuned embeddings

    # Record the pretrained GAT hash for later verification
    pre_gat_hash = _param_hash(pre_model.amsgp.node_embedding_layers._layers)
    del pre_model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # ── Step 1b: extract signals from the fine-tuned model ────────────
    logger.info(f"\n  [Step 1b] Extracting embeddings from FINE-TUNED model ...")
    ft_model = load_finetuned_for_extraction(
        pretrained_model, ft_ckpt_path, litdata_dir, config,
        finetune_log_dir=finetune_log_dir,
        map_location=str(device),
    )
    ft_model = ft_model.to(device)
    ft_model.eval()

    # [BUG-3] Verify that the GAT weights differ after fine-tuning
    ft_gat_hash = _param_hash(ft_model.amsgp.node_embedding_layers._layers)
    if pre_gat_hash == ft_gat_hash:
        logger.error(
            "  ✗ CRITICAL: GAT weights are IDENTICAL!\n"
            "  The fine-tuned model's GAT layers have the same weights as "
            "the pretrained model.\n"
            "  Possible causes: (1) wrong checkpoint path, "
            "(2) load_state_dict failed silently.\n"
            "  Aborting extraction — Δ would be meaningless."
        )
        return None
    else:
        logger.success(
            f"  ✓ GAT weights verified different "
            f"(pre={pre_gat_hash}, ft={ft_gat_hash})"
        )

    gene_emb_ft, edge_pairs_ft, cell_emb_ft_list = extract_signals_from_dataloader(
        ft_model, all_dataloaders, dict_node_names, device=device,
    )

    # [NEW] Convert the cell embedding list into a numpy array
    if cell_emb_ft_list:
        cell_embeddings_ft = np.stack(cell_emb_ft_list, axis=0)
        logger.info(
            f"  Cell embeddings (fine-tuned): {cell_embeddings_ft.shape[0]} cells, "
            f"dim={cell_embeddings_ft.shape[1]}"
        )
    else:
        cell_embeddings_ft = None
        logger.warning("  No cell embeddings collected from fine-tuned model.")

    del ft_model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # ── Step 2: aggregate signals and compute cosine-similarity edge weights ──
    logger.info(f"\n  [Step 2] Aggregating signals ...")

    logger.info(f"  --- Pretrained ---")
    mean_emb_pre, edges_pre, w_pre = aggregate_signals(
        gene_emb_pre, edge_pairs_pre, gene_id_to_name,
    )
    logger.info(f"  --- Fine-tuned ---")
    mean_emb_ft, edges_ft, w_ft = aggregate_signals(
        gene_emb_ft, edge_pairs_ft, gene_id_to_name,
    )

    if len(edges_pre) == 0 or len(edges_ft) == 0:
        logger.error("  No edges after aggregation. Aborting.")
        return None

    # ── Step 3: compute delta weights ─────────────────────────────────
    logger.info(f"\n  [Step 3] Computing Δw ...")
    common_edges, delta_w, w_pre_aligned, w_ft_aligned = compute_delta(
        w_pre, edges_pre, w_ft, edges_ft,
    )

    if len(common_edges) == 0:
        logger.error("  No common edges found. Aborting.")
        return None

    # ── Step 4: build the CSN network ─────────────────────────────────
    logger.info(f"\n  [Step 4] Building CSN network ...")
    network = build_network(
        common_edges, delta_w, w_pre_aligned, w_ft_aligned,
        gene_id_to_name,
    )

    # ── Additional statistics ─────────────────────────────────────────
    extra_stats = {
        "delta_w_mean": round(float(delta_w.mean()), 8),
        "delta_w_std": round(float(delta_w.std()), 8),
        "delta_w_median": round(float(np.median(delta_w)), 8),
        "delta_w_positive_frac": round(
            float((delta_w > 0).sum() / len(delta_w)), 4
        ),
        "w_ft_negative_frac": round(
            float((w_ft_aligned < 0).sum() / len(w_ft_aligned)), 4
        ),
        "n_pre_edges": len(edges_pre),
        "n_ft_edges": len(edges_ft),
        "n_common_edges": len(common_edges),
        "n_cells": int(cell_embeddings_ft.shape[0]) if cell_embeddings_ft is not None else 0,
    }

    # ── Raw signals for diagnostics and reanalysis ────────────────────
    raw_signals = {
        "common_edges": common_edges,
        "sim_pre": w_pre_aligned,
        "sim_ft": w_ft_aligned,
        "delta_w": delta_w,
        "w_pre": w_pre_aligned,
        "w_ft": w_ft_aligned,
    }

    # ── Step 5: save outputs ──────────────────────────────────────────
    logger.info(f"\n  [Step 5] Saving outputs ...")
    out_dir = save_csn_output(
        output_dir=config["output_dir"],
        cell_group_name=cell_group_name,
        split_id=split_id,
        network=network,
        mean_embeddings_pre=mean_emb_pre,
        mean_embeddings_ft=mean_emb_ft,
        gene_id_to_name=gene_id_to_name,
        config=config,
        raw_signals=raw_signals,
        extra_stats=extra_stats,
        cell_embeddings_ft=cell_embeddings_ft,
    )

    logger.success(f"  ✓ CSN extraction complete for {display_name}")
    return out_dir


# ============================================================================
# 7. Legacy split discovery
# ============================================================================

def _discover_splits(litdata_base: str) -> List[str]:
    """Discover legacy split subdirectories using the same layout as cell fine-tuning."""
    pkl_name = const.fname.litdata_others2save_pkl
    if os.path.exists(os.path.join(litdata_base, pkl_name)):
        return []
    if not os.path.isdir(litdata_base):
        return []
    splits = []
    for entry in os.listdir(litdata_base):
        subdir = os.path.join(litdata_base, entry)
        if os.path.isdir(subdir) and os.path.exists(
            os.path.join(subdir, pkl_name)
        ):
            splits.append(entry)

    def _sort_key(s):
        try:
            return (0, int(s), s)
        except ValueError:
            return (1, 0, s)

    splits.sort(key=_sort_key)
    return splits


def _find_best_ckpt(
    cell_group_dir: str,
    split_id: Optional[str] = None,
) -> Optional[str]:
    """Find the best checkpoint in an output directory by sorting on val_loss when available."""
    search_dir = os.path.join(cell_group_dir, split_id) if split_id else cell_group_dir
    if not os.path.isdir(search_dir):
        return None

    ckpt_files = []
    for root, dirs, files in os.walk(search_dir):
        for f in files:
            if f.endswith(".ckpt"):
                ckpt_files.append(os.path.join(root, f))

    if not ckpt_files:
        return None

    def _extract_loss(path):
        name = os.path.basename(path)
        try:
            if "val_loss=" in name:
                loss_str = name.split("val_loss=")[1].split(".ckpt")[0]
                return float(loss_str)
        except (IndexError, ValueError):
            pass
        return float("inf")

    ckpt_files.sort(key=_extract_loss)
    return ckpt_files[0]


# ============================================================================
# 8. Main entry point
# ============================================================================

def _resolve_device(config: Dict[str, Any]) -> torch.device:
    """Resolve inference device from config."""
    accelerator = str(config.get("accelerator", "auto")).lower()
    if accelerator == "gpu" and torch.cuda.is_available():
        return torch.device("cuda:0")
    if accelerator == "auto" and torch.cuda.is_available():
        return torch.device("cuda:0")
    return torch.device("cpu")


def _process_single_run(
    args: argparse.Namespace,
    config: Dict[str, Any],
    pretrained_model: DeepTAN,
    device: torch.device,
) -> Dict[str, str]:
    """Run the user-facing single-run extraction workflow."""
    cell_group_name = (
        args.cell_group
        or config.get("cell_group_name")
        or "CellGroup"
    )
    split_id = args.split or config.get("split_id")
    split_id = str(split_id) if split_id is not None and str(split_id) != "" else None

    litdata_dir = args.litdata_dir or config.get("litdata_dir", "")
    ft_ckpt = args.ft_ckpt or args.finetuned_ckpt or config.get("finetuned_ckpt", "")
    output_dir_override = args.output_dir

    if output_dir_override:
        config["output_dir"] = output_dir_override

    if not litdata_dir:
        raise ValueError(
            "No LitData directory provided. Set config.litdata_dir or pass --litdata_dir."
        )
    if not os.path.isdir(litdata_dir):
        raise FileNotFoundError(f"LitData directory not found: {litdata_dir}")

    pkl_path = os.path.join(litdata_dir, const.fname.litdata_others2save_pkl)
    if not os.path.exists(pkl_path):
        raise FileNotFoundError(
            f"LitData metadata not found: {pkl_path}\n"
            "Run03 expects a Run01 output directory containing trn/, val/, tst/ "
            f"and {const.fname.litdata_others2save_pkl}."
        )

    if not ft_ckpt:
        raise ValueError(
            "No fine-tuned checkpoint provided. Set config.finetuned_ckpt or pass --finetuned_ckpt."
        )
    if not os.path.exists(ft_ckpt):
        raise FileNotFoundError(f"Fine-tuned checkpoint not found: {ft_ckpt}")

    logger.info("=" * 70)
    logger.info("Run03 | Cell-Specific Network Extraction | Single-run mode")
    logger.info("=" * 70)
    logger.info(f"cell_group_name : {cell_group_name}")
    logger.info(f"split_id        : {split_id or '<not used>'}")
    logger.info(f"litdata_dir     : {litdata_dir}")
    logger.info(f"finetuned_ckpt  : {ft_ckpt}")
    logger.info(f"output_dir      : {config['output_dir']}")
    logger.info(f"simple_output   : {config.get('simple_output', False)}")
    logger.info("=" * 70)

    out_dir = process_single_cell_group(
        cell_group_name=cell_group_name,
        split_id=split_id,
        pretrained_model=pretrained_model,
        ft_ckpt_path=ft_ckpt,
        litdata_dir=litdata_dir,
        config=config,
        device=device,
    )

    return {cell_group_name: out_dir} if out_dir else {}


def _process_legacy_cell_groups(
    args: argparse.Namespace,
    config: Dict[str, Any],
    pretrained_model: DeepTAN,
    device: torch.device,
) -> Dict[str, str]:
    """Run the original multi-cell-group / multi-split workflow."""
    cell_group_names = (
        [args.cell_group] if args.cell_group
        else config.get("cell_group_order", [])
    )
    finetune_output_dir = config.get("finetune_output_dir", "")

    all_outputs = {}

    for cell_group_name in cell_group_names:
        cell_group_cfg = config.get("cell_groups", {}).get(cell_group_name, {})
        litdata_base = cell_group_cfg.get("litdata", "")
        split_from_cfg = str(cell_group_cfg.get("split")) if cell_group_cfg.get("split") is not None else None
        ft_ckpt_from_cfg = cell_group_cfg.get("ft_ckpt", None)

        if not litdata_base:
            logger.error(f"No litdata for '{cell_group_name}'. Skipping.")
            continue

        splits = _discover_splits(litdata_base)

        if splits:
            if args.split:
                splits = [s for s in splits if s == args.split]

            for split_id in splits:
                split_litdata = os.path.join(litdata_base, split_id)

                if args.ft_ckpt or args.finetuned_ckpt:
                    ft_ckpt = args.ft_ckpt or args.finetuned_ckpt
                elif ft_ckpt_from_cfg:
                    ft_ckpt = ft_ckpt_from_cfg
                else:
                    cell_group_out = os.path.join(finetune_output_dir, cell_group_name)
                    ft_ckpt = _find_best_ckpt(cell_group_out, split_id)

                if not ft_ckpt or not os.path.exists(ft_ckpt):
                    logger.error(
                        f"  Checkpoint not found for "
                        f"{cell_group_name}/{split_id}. "
                        f"Use --ft_ckpt or --finetuned_ckpt to specify directly."
                    )
                    continue

                try:
                    out_dir = process_single_cell_group(
                        cell_group_name, split_id,
                        pretrained_model, ft_ckpt, split_litdata,
                        config, device,
                    )
                    if out_dir:
                        all_outputs[f"{cell_group_name}/{split_id}"] = out_dir
                except Exception as e:
                    logger.error(
                        f"  Failed for {cell_group_name}/{split_id}: {e}"
                    )
                    import traceback
                    traceback.print_exc()
        else:
            if args.ft_ckpt or args.finetuned_ckpt:
                ft_ckpt = args.ft_ckpt or args.finetuned_ckpt
            elif ft_ckpt_from_cfg:
                ft_ckpt = ft_ckpt_from_cfg
            else:
                cell_group_out = os.path.join(finetune_output_dir, cell_group_name)
                ft_ckpt = _find_best_ckpt(cell_group_out, split_from_cfg)

            if not ft_ckpt or not os.path.exists(ft_ckpt):
                logger.error(
                    f"  Checkpoint not found for {cell_group_name}. "
                    f"Use --ft_ckpt or --finetuned_ckpt to specify directly."
                )
                continue

            try:
                out_dir = process_single_cell_group(
                    cell_group_name, args.split or split_from_cfg,
                    pretrained_model, ft_ckpt, litdata_base,
                    config, device,
                )
                if out_dir:
                    all_outputs[cell_group_name] = out_dir
            except Exception as e:
                logger.error(f"  Failed for {cell_group_name}: {e}")
                import traceback
                traceback.print_exc()

    return all_outputs


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Run03: extract a cell-specific latent gene network from a "
            "cell-type fine-tuned DeepTAN checkpoint."
        )
    )
    parser.add_argument("--config", type=str, required=True, help="Path to cell network extraction YAML config.")
    parser.add_argument("--cell_group", type=str, default=None, help="Optional cell group/run name override.")
    parser.add_argument("--split", type=str, default=None, help="Optional split/run identifier. Used mainly for legacy batch outputs.")
    parser.add_argument("--ft_ckpt", type=str, default=None, help="Alias for --finetuned_ckpt; kept for backward compatibility.")
    parser.add_argument("--finetuned_ckpt", type=str, default=None, help="Fine-tuned checkpoint generated by Run02.")
    parser.add_argument("--litdata_dir", type=str, default=None, help="LitData directory generated by Run01.")
    parser.add_argument("--output_dir", type=str, default=None, help="Override config.output_dir.")
    parser.add_argument(
        "--legacy_multi_group",
        action="store_true",
        help=(
            "Use the legacy cell_groups/cell_group_order workflow. "
            "The default workflow is single-run via litdata_dir + finetuned_ckpt."
        ),
    )
    args = parser.parse_args()

    config = load_csn_config(args.config)

    if args.output_dir:
        config["output_dir"] = args.output_dir

    device = _resolve_device(config)
    logger.info(f"Device: {device}")

    pretrained_ckpt = config.get("pretrained_ckpt", "")
    if not pretrained_ckpt:
        raise ValueError("config.pretrained_ckpt is required.")
    if not os.path.exists(pretrained_ckpt):
        raise FileNotFoundError(f"Pretrained checkpoint not found: {pretrained_ckpt}")

    pretrained_model = load_pretrained_for_extraction(pretrained_ckpt, str(device))

    # Single-run is the GitHub-facing default. Legacy multi-group is still
    # available for internal batch experiments.
    use_single_run = not args.legacy_multi_group and (
        bool(args.litdata_dir)
        or bool(args.finetuned_ckpt)
        or bool(config.get("litdata_dir"))
        or bool(config.get("finetuned_ckpt"))
    )

    if use_single_run:
        all_outputs = _process_single_run(args, config, pretrained_model, device)
    else:
        logger.info("Using legacy multi-cell-group mode.")
        all_outputs = _process_legacy_cell_groups(args, config, pretrained_model, device)

    logger.info(f"\n{'=' * 70}")
    logger.info("  CELL-SPECIFIC NETWORK EXTRACTION COMPLETE")
    logger.info(f"{'=' * 70}")
    for key, path in all_outputs.items():
        logger.info(f"  {key}: {path}")

    summary_path = os.path.join(config["output_dir"], "csn_summary.yaml")
    os.makedirs(os.path.dirname(summary_path), exist_ok=True)
    with open(summary_path, "w") as f:
        yaml.safe_dump(all_outputs, f, default_flow_style=False, allow_unicode=True)
    logger.success(f"Summary: {summary_path}")


if __name__ == "__main__":
    main()
