r"""
Dictionary keys and column names.
"""

litdata_id = "id"
litdata_index = "index"
litdata_label = "label"
litdata_omics = "omics"
omics_dim = "omics_dim"
omics_feature = "omics_feature"
model_output_dim = "model_output_dim"

id = "ID"
label = "label"
ckpt_path = "path_ckpt"
which_outer = "x_outer"
which_inner = "x_inner"
val_loss = "val_loss"

lr = "lr"
patience = "patience"
max_epochs = "max_epochs"
min_epochs = "min_epochs"
bsize = "batch_size"
hidden_dim = "hidden_dim"
num_heads = "n_heads"
num_encoders = "n_encoders"
dropout = "dropout"
