import argparse
import json
import os
import pickle
import shutil
import sys

import litdata
import numpy as np
import polars as pl
import scanpy as sc

import deeptan.constants as const
from deeptan.graph.model import DeepTANTune
from deeptan.graph.recon import compute_feature_correlations, predict
from deeptan.utils.data import DeepTANDataModule, read_nmic_npz


def hello():
    print(const.art.ascii_art)
    print("\nHello, DeepTAN!\n")


def print_h5():
    parser = argparse.ArgumentParser(description="Read an H5AD or H5 file and print its contents.")
    parser.add_argument("-p", "--path", type=str, help="Path to the H5AD or H5 file.")
    args = parser.parse_args()
    if args.path.endswith(".h5ad"):
        adata = sc.read_h5ad(args.path)
    elif args.path.endswith(".h5"):
        adata = sc.read_10x_h5(args.path)
    else:
        print("Unsupported file format. Please provide a .h5ad or .h5 file.")
        sys.exit(1)
    print(adata)
    print("\nobs keys: ")
    print(adata.obs.keys())
    for _key in adata.obs.keys():
        print(f"\n{_key}:")
        print(adata.obs[_key])
    print("\nvar keys: ")
    for _key in adata.var_keys():
        print(f"\n{_key}:")
        print(adata.var[_key])
    if "Celltype" in adata.obs.keys():
        print("\nCelltype:")
        print(type(adata.obs["Celltype"]))
    if "Orig.ident" in adata.obs.keys():
        sc.pl.umap(adata, color="Orig.ident", title="UMAP by Experiment")


def deeptan_optimize_data():
    parser = argparse.ArgumentParser(description="Optimize data for Deeptan model")
    parser.add_argument("--labels", type=str, default="", help="Path to label data in .parquet format")
    parser.add_argument("--bs", type=int, default=const.default.bs, help="Batch size for training")
    parser.add_argument("--trn_npz", type=str, required=True, help="Path to training data in .npz format (generated by mi2graph)")
    parser.add_argument("--val_parquet", type=str, required=True, help="Path to validation data in .parquet format")
    parser.add_argument("--tst_parquet", type=str, required=True, help="Path to test data in .parquet format")
    parser.add_argument("--output_dir", type=str, default=".tmp_data_optimized", help="Directory for logging")
    parser.add_argument("--thre_mi", type=float, default=const.default.threshold_nmic, help="Threshold for edge attribute")
    parser.add_argument("--in_feat", type=str, default="", help="Path to a .csv with header, containing a list of features to specify. If None, all features are used")
    parser.add_argument("--in_obs", type=str, default="", help="")
    parser.add_argument("--onlytest", action="store_true", help="Only run the test phase")
    parser.add_argument("--n_workers", type=int, default=const.default.n_threads, help="Number of workers for data loading")
    args = parser.parse_args()

    if len(args.labels) < 2:
        labels = None
    else:
        labels = args.labels

    if len(args.in_feat) < 2:
        specify_features = None
    else:
        specify_features = args.in_feat

    if len(args.in_obs) < 2:
        specify_trn_obs = None
    else:
        specify_trn_obs = args.in_obs

    files_fit = {
        const.dkey.abbr_train: args.trn_npz,
        const.dkey.abbr_val: args.val_parquet,
        const.dkey.abbr_test: args.tst_parquet,
    }
    datamodule = DeepTANDataModule(
        files_fit,
        labels,
        batch_size=args.bs,
        edge_attr_threshold=args.thre_mi,
        specify_features=specify_features,
    )
    datamodule.setup()

    # Copy original training data to output directory for saving node_names and g_label_dim
    # shutil.copy(args.trn_npz, os.path.join(args.output_dir, "trn.npz"))
    others2save = {
        "dict_node_names": datamodule.dict_node_names,
        "output_g_label_dim": datamodule.label_dim,
    }
    os.makedirs(args.output_dir, exist_ok=True)
    # Save as json
    with open(os.path.join(args.output_dir, const.fname.litdata_others2save_json), "w") as f:
        json.dump(others2save, f)
    # Save as pickle
    with open(os.path.join(args.output_dir, const.fname.litdata_others2save_pkl), "wb") as f:
        pickle.dump(others2save, f)

    if labels is not None:
        shutil.copy(labels, os.path.join(args.output_dir, const.fname.label_class_onehot))

    # Check obs_names filter
    if specify_trn_obs is not None:
        _edge_attr, _edge_index, _mat, _mat_feat_indices, _obs_names, _node_names = read_nmic_npz(args.trn_npz)
        _obs_names_goal = pl.read_parquet(specify_trn_obs)["obs_names"].to_list()
        # Get intersection of _obs_names and _obs_names_goal
        _obs_names_filtered = list(set(_obs_names) & set(_obs_names_goal))
        # Get available indices in _obs_names for the following litdata getting indices
        _obs_names_indices = np.where(np.isin(_obs_names, _obs_names_filtered))[0]
        _trn_indices = _obs_names_indices.tolist()
    else:
        _trn_indices = list(range(datamodule.train.len()))

    # Optimize
    if not args.onlytest:
        litdata.optimize(
            fn=datamodule.train.get,
            inputs=_trn_indices,
            output_dir=os.path.join(args.output_dir, const.dkey.abbr_train),
            chunk_bytes=const.default.lit_chunk_bytes,
            compression=const.default.lit_compression,
            num_workers=min(args.n_workers, const.default.n_threads),
        )
        litdata.optimize(
            fn=datamodule.val.get,
            inputs=list(range(datamodule.val.len())),
            output_dir=os.path.join(args.output_dir, const.dkey.abbr_val),
            chunk_bytes=const.default.lit_chunk_bytes,
            compression=const.default.lit_compression,
            num_workers=min(args.n_workers, const.default.n_threads),
        )
    litdata.optimize(
        fn=datamodule.test.get,
        inputs=list(range(datamodule.test.len())),
        output_dir=os.path.join(args.output_dir, const.dkey.abbr_test),
        chunk_bytes=const.default.lit_chunk_bytes,
        compression=const.default.lit_compression,
        num_workers=min(args.n_workers, const.default.n_threads),
    )


def deeptan_fit_tune():
    parser = argparse.ArgumentParser(description="DeepTAN fitting and tuning pipeline.")
    parser.add_argument("--auto_tune", "--atune", action="store_true", help="Whether to perform hyperparameter tuning")

    parser.add_argument("--em", type=str, default="", help="Existing model checkpoint path for loading")
    parser.add_argument("--focus", type=str, default="None", help="Focus on a specific task, choose from 'None', 'recon', 'label', 'recon_and_freeze', 'label_and_freeze'")
    parser.add_argument("--no_guide_gat", "--nog", action="store_true", help="Whether to disable edge weights of guidance graphs on graph attentions")

    parser.add_argument("--litdata", "--data", type=str, required=False, help="Path to litdata directory")
    parser.add_argument("--bs", type=int, default=const.default.bs, help="Batch size for training")
    parser.add_argument("--lr", type=float, default=const.default.lr, help="Learning rate")
    parser.add_argument("--log_dir", "--logdir", type=str, default=".tmp_logs_tune", help="Directory for logging")
    parser.add_argument("--input_node_emb_dim", "--indim", type=int, default=1, help="Input node embedding dimension")
    parser.add_argument("--is_regression", "--ir", action="store_true", help="Whether the task is regression")
    parser.add_argument("--acc_grad_batch", "--agb", type=int, default=const.default.accumulate_grad_batches, help="Accumulate gradients over multiple batches")
    parser.add_argument("--chunk_size", "--ck", type=int, default=const.default.chunk_size, help="A proper chunk size can balance memory usage and speed")
    parser.add_argument("--accelerator", "--ac", type=str, default=const.default.accelerator, help="cpu, gpu, tpu, hpu, mps, auto")
    parser.add_argument("--devices", "--dev", type=str, default=const.default.devices, help="Devices to use")
    parser.add_argument("--ntrials", "--nt", type=int, default=const.default.n_trials, help="Number of trials for hyperparameter tuning")
    parser.add_argument("--njobs", "--nj", type=int, default=const.default.n_jobs, help="The number of parallel jobs for Optuna. If this argument is set to -1, the number is set to CPU count.")
    args = parser.parse_args()

    if args.no_guide_gat:
        guide_gat = False
    else:
        guide_gat = True

    _config = const.default.model_config.copy()
    _config.update(
        {
            "es": const.default.es,
            "max_ep": const.default.max_epoch,
            "min_ep": const.default.min_epoch,
            "log_dir": args.log_dir,
            "litdata": args.litdata,
            "bs": args.bs,
            "lr": args.lr,
            "chunk_size": args.chunk_size,
            "is_regression": args.is_regression,
            "accelerator": args.accelerator,
            "devices": args.devices,
            "input_node_emb_dim": args.input_node_emb_dim,
            "acc_grad_batch": args.acc_grad_batch,
            "guide_gat": guide_gat,
        }
    )
    print(f"\n🔧Configuration⚙️\n{_config}\n")

    if len(args.em) < 3:
        ckpt = None
    else:
        ckpt = args.em

    if args.focus == "None":
        focus = None
    else:
        focus = args.focus

    trainer = DeepTANTune(_config, ckpt, focus)
    if args.auto_tune:
        trainer.optimize(n_trials=args.ntrials, n_jobs=args.njobs)
    else:
        trainer._train_on_args()


def deeptan_predict():
    parser = argparse.ArgumentParser(description="DeepTAN prediction script.")
    parser.add_argument("--em", type=str, required=True, help="Existing model checkpoint path.")
    parser.add_argument("--litdata", "--data", type=str, required=True, help="Path to litdata directory")
    parser.add_argument("--output", "--out", type=str, required=True, help="Path to output pickle file")
    parser.add_argument("--maplocation", "--maploc", type=str, default=None, help="Map location for model loading")
    parser.add_argument("--getcor", action="store_true", help="Get correlations between feature pairs and labels")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing output directory")
    args = parser.parse_args()

    model_path = args.em
    litdata_dir = args.litdata

    # Create output directory
    output_dir = os.path.dirname(args.output)
    os.makedirs(output_dir, exist_ok=True)
    output_pkl_path = args.output
    if not output_pkl_path.endswith(".pkl"):
        output_pkl_path += ".pkl"

    if not os.path.exists(output_pkl_path) or args.overwrite:
        print(f"Predicting with model {model_path} on data {litdata_dir}")
        predict(
            model_ckpt_path=model_path,
            litdata_dir=litdata_dir,
            output_pkl_path=output_pkl_path,
            map_location=args.map_location,
            batch_size=8,
        )
    else:
        print(f"Results already exist at {output_pkl_path}")

    if args.getcor:
        output_cor_mat = os.path.join(os.path.dirname(output_pkl_path), os.path.basename(output_pkl_path) + "." + "correlation_matrix.npz")
        if not os.path.exists(output_cor_mat) or args.overwrite:
            compute_feature_correlations(output_cor_mat, output_pkl_path)
        else:
            print(f"Correlation matrix already exists at {output_cor_mat}")
