#!/usr/bin/env python3
r"""
==============================================================================
Run02: Trait-Aware BulkExpand-DeepTAN Fine-Tuning
==============================================================================

Purpose
-------
Fine-tune an scRNA-pretrained DeepTAN model on one trait-aware bulk LitData
directory generated by Run01.

Pipeline position
-----------------
Run01: user-defined bulk files -> bulk-expanded LitData
Run02: LitData -> trait-aware bulk fine-tuned DeepTAN checkpoint
Run03: LitData + fine-tuned checkpoint -> trait-aware latent gene network
Run04: trait-aware network -> downstream module / hub / gene-set analysis

Core workflow
-------------
This script performs model fine-tuning only. It does not rebuild LitData and
does not recompute the NMIC graph.

Main steps:
  1. Load an scRNA-pretrained DeepTAN checkpoint.
  2. Load the expanded metadata generated by Run01.
  3. Expand the pretrained node vocabulary and embedding layer to include bulk
     features.
  4. Copy and protect old-gene embeddings while initializing new bulk-feature
     embeddings from graph neighbors when possible.
  5. Fine-tune the model with FT16 continuous trait regression as trait-aware
     supervision and observed-node reconstruction as an auxiliary task.
  6. Use DeepTAN-style epoch-level task alternation to improve comparability
     with a bulk-from-scratch DeepTAN baseline.
  7. Report public label-regression metrics as
     label_regression_MSE / MAE / PCC / RMSE.
  8. Support parameter anchoring, old-embedding anchoring, and new-embedding
     smoothness regularization.
  9. Save checkpoints, prediction files, metrics, and fine-tuning metadata.

Evaluation note
---------------
For random-sample bulk fine-tuning, FT16 regression metrics are diagnostic
signals showing whether the model learns trait-aware supervision. Final
scientific interpretation should focus on the biological plausibility and
cross-run stability of the extracted trait-associated network.

Input requirement
-----------------
The input dataset_root must point to a Run01 output directory that directly
contains trn/, val/, tst/, and expanded_metadata.pkl. A legacy seed_<id>
subdirectory layout is still supported for backward compatibility.

Author: DeepTAN Bulk Fine-Tuning Pipeline
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import os
import pickle
import re
import sys

# # ── Prefer the local DeepTAN source tree when available ───────────────
# _LOCAL_DEEPTAN = "path/deeptan-dev/src"
# if _LOCAL_DEEPTAN not in sys.path:
#     sys.path.insert(0, _LOCAL_DEEPTAN)
# # ────────────────────────────────────────────────────────────────────────────
from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple

import litdata
import numpy as np
import polars as pl
import torch
import torch.nn as nn
import torch.nn.functional as F
import yaml
from lightning import LightningModule, Trainer, seed_everything
from lightning.pytorch.callbacks import EarlyStopping, LearningRateMonitor, ModelCheckpoint
from lightning.pytorch.loggers import TensorBoardLogger
from loguru import logger
from torch.optim.adamw import AdamW
from torch_geometric.data import Data as GData


DEFAULT_CONFIG: Dict[str, Any] = {
    "local_deeptan_src": "",
    "pretrained_ckpt": "",
    "dataset_root": "",
    "output_dir": "",
    # Optional human-readable identifier for this single run.
    "data_id": "bulk_run",
    # Legacy compatibility only: if dataset_root does not directly contain trn/val/tst,
    # the loader may fall back to dataset_root/seed_<first seeds entry>.
    "seeds": [],
    "run_name": "TraitBulkDeepTAN",
    "accelerator": "gpu",
    "devices": 1,
    "precision": "16-mixed",
    "batch_size": 16,
    "n_workers": 8,
    "max_epochs": 80,
    "min_epochs": 10,
    "es_patience": 12,
    "gradient_clip_val": 1.0,
    "accumulate_grad_batches": 1,
    "base_lr": 3.0e-5,
    "weight_decay": 1.0e-5,
    "warmup_epochs": 3,
    "scheduler": "cosine_warm_restarts",
    "cosine_T0": 12,
    "cosine_T_mult": 1,
    "plateau_patience": 5,
    "plateau_factor": 0.5,
    "min_lr": 1.0e-7,
    "lr_multipliers": {
        "old_embedding_effective": 0.03,
        "new_embedding_effective": 1.0,
        "feature_proj": 0.10,
        "fusion_mlp": 0.10,
        "gat_layers": 0.20,
        "pooling": 0.20,
        "ge_decoder": 0.30,
        "trait_predictor": 1.00,
    },
    "loss": {
        "lambda_reg": 1.0,
        "lambda_recon": 0.20,
        "lambda_anchor": 0.02,
        "lambda_old_embedding_anchor": 0.02,
        "lambda_new_smoothness": 0.01,
        "use_zero_penalty": False,
        "lambda_zero": 0.0,
    },
    "task_balance": {
        # joint: fixed joint optimization for every epoch.
        # cycle: DeepTAN-style epoch-level task alternation for fairer comparison with from-scratch DeepTAN.
        "strategy": "cycle",  # cycle | joint
        "warmup_recon_epochs": 3,
        "cycle": ["recon", "regress", "joint"],
        "recon_focus_reg_weight": 0.0,
        "recon_focus_recon_weight": 1.0,
        "regress_focus_reg_weight": 1.0,
        "regress_focus_recon_weight": 0.0,
        "joint_reg_weight": 1.0,
        "joint_recon_weight": 1.0,
        "regularization_in_all_phases": True,
    },
    # Skip expensive GE decoder when reconstruction is not part of the active objective.
    # This mainly accelerates regress-only phases and validation/test, because FT16
    # metrics do not require feature reconstruction. Set eval_compute_recon=True
    # only when validation/test reconstruction losses are explicitly needed.
    "skip_decoder_when_unused": True,
    "eval_compute_recon": True,
    "num_sanity_val_steps": 0,
    "check_val_every_n_epoch": 1,
    "stages": {
        "new_assimilation_epochs": 3,
        "old_embedding_scale_stage1": 0.0,
        "new_embedding_scale_stage1": 1.0,
        "old_embedding_scale_after": 0.03,
        "new_embedding_scale_after": 1.0,
    },
    "seed": 42,
}


def deep_update(base: Dict[str, Any], upd: Dict[str, Any]) -> Dict[str, Any]:
    for k, v in (upd or {}).items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            base[k] = deep_update(base[k], v)
        else:
            base[k] = v
    return base


def load_config(path: str) -> Dict[str, Any]:
    cfg = copy.deepcopy(DEFAULT_CONFIG)
    with open(path, "r") as f:
        user_cfg = yaml.safe_load(f) or {}
    cfg = deep_update(cfg, user_cfg)
    # Compatible with the dataset-builder style config where the checkpoint lives under pretrained.checkpoint.
    if not cfg.get("pretrained_ckpt") and isinstance(cfg.get("pretrained"), dict):
        cfg["pretrained_ckpt"] = cfg["pretrained"].get("checkpoint", "")
    return cfg


def setup_deeptan_path(local_src: str):
    if local_src and local_src not in sys.path:
        sys.path.insert(0, local_src)


def collate_fn(data_list):
    from torch_geometric.data import Batch as GBatch
    return GBatch.from_data_list(data_list)


# -----------------------------------------------------------------------------
# Metrics helpers
# -----------------------------------------------------------------------------


def _rankdata_average(x: np.ndarray) -> np.ndarray:
    order = np.argsort(x)
    ranks = np.empty_like(order, dtype=np.float64)
    ranks[order] = np.arange(len(x), dtype=np.float64)
    # average ties
    vals, starts, counts = np.unique(x[order], return_index=True, return_counts=True)
    for st, ct in zip(starts, counts):
        if ct > 1:
            idx = order[st : st + ct]
            ranks[idx] = ranks[idx].mean()
    return ranks


def corrcoef_safe(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    if a.size < 2 or np.std(a) < 1e-12 or np.std(b) < 1e-12:
        return float("nan")
    return float(np.corrcoef(a, b)[0, 1])


def regression_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    err = y_pred - y_true
    mse = float(np.mean(err ** 2)) if y_true.size else float("nan")
    mae = float(np.mean(np.abs(err))) if y_true.size else float("nan")
    rmse = float(math.sqrt(mse)) if np.isfinite(mse) else float("nan")
    denom = float(np.sum((y_true - y_true.mean()) ** 2)) if y_true.size else 0.0
    r2 = float(1.0 - np.sum(err ** 2) / denom) if denom > 1e-12 else float("nan")
    pearson = corrcoef_safe(y_true, y_pred)
    spearman = corrcoef_safe(_rankdata_average(y_true), _rankdata_average(y_pred)) if y_true.size else float("nan")
    return {"Pearson": pearson, "Spearman": spearman, "RMSE": rmse, "MAE": mae, "MSE": mse, "R2": r2}


def named_regression_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
    """Return the comparable regression metrics used in DeepTAN reports.

    The bulk-from-scratch DeepTAN regression table reports MSE, MAE, PCC and
    RMSE for both label prediction and reconstruction.  This helper intentionally
    returns only these four comparable metrics so that fine-tuning outputs do not
    mix final task metrics with internal train-scale losses.
    """
    metrics = regression_metrics(y_true, y_pred)
    return {
        "MSE": metrics["MSE"],
        "MAE": metrics["MAE"],
        "PCC": metrics["Pearson"],
        "RMSE": metrics["RMSE"],
    }


def flatten_metrics(prefix: str, metrics: Optional[Dict[str, float]]) -> Dict[str, float]:
    """Flatten a metric dict into prefix_metric_name keys for CSV summaries."""
    if not metrics:
        return {}
    return {f"{prefix}_{k}": float(v) for k, v in metrics.items()}


# -----------------------------------------------------------------------------
# Model expansion helpers
# -----------------------------------------------------------------------------


def load_pretrained_model(ckpt_path: str):
    from deeptan.graph.model import DeepTAN  # type: ignore

    model_dir = os.path.dirname(ckpt_path)
    hparams_path = os.path.join(model_dir, "version_0", "hparams.yaml")
    kwargs = {"map_location": "cpu"}
    if os.path.exists(hparams_path):
        kwargs["hparams_file"] = hparams_path
    logger.info(f"Loading pretrained DeepTAN: {ckpt_path}")
    model = DeepTAN.load_from_checkpoint(ckpt_path, **kwargs)
    model.eval()
    return model


def find_last_linear(module: nn.Module) -> Tuple[str, nn.Linear]:
    last_name = None
    last_linear = None
    for name, m in module.named_modules():
        if isinstance(m, nn.Linear):
            last_name = name
            last_linear = m
    if last_linear is None or last_name is None:
        raise RuntimeError("No Linear layer found in predictor")
    return last_name, last_linear


def set_submodule(root: nn.Module, path: str, new_module: nn.Module):
    parts = path.split(".") if path else []
    if not parts:
        raise ValueError("Cannot replace root module")
    parent = root
    for p in parts[:-1]:
        parent = parent[int(p)] if p.isdigit() else getattr(parent, p)
    last = parts[-1]
    if last.isdigit():
        parent[int(last)] = new_module
    else:
        setattr(parent, last, new_module)


def initialize_new_embeddings_from_edges(
    old_weight: torch.Tensor,
    meta: Dict[str, Any],
    seed_dir: str,
    noise_scale: float = 0.02,
) -> torch.Tensor:
    expanded_dict = meta["dict_node_names"]
    n_old = int(meta["num_old_nodes"])
    n_all = len(expanded_dict)
    d = old_weight.shape[1]
    new_init = old_weight.mean(dim=0).repeat(n_all - n_old, 1)

    edge_path = os.path.join(seed_dir, "edge_source.parquet")
    if os.path.exists(edge_path):
        edge_df = pl.read_parquet(edge_path)
        old_set = set(range(n_old))
        accum = torch.zeros_like(new_init)
        denom = torch.zeros(n_all - n_old, dtype=torch.float32)
        # Use old-new edges. If src new / dst old or reverse, accumulate old embedding.
        for row in edge_df.select(["src_expanded_idx", "dst_expanded_idx", "edge_weight"]).iter_rows():
            s, t, w = int(row[0]), int(row[1]), float(row[2])
            if s >= n_old and t in old_set:
                j = s - n_old
                accum[j] += old_weight[t] * w
                denom[j] += abs(w)
            elif t >= n_old and s in old_set:
                j = t - n_old
                accum[j] += old_weight[s] * w
                denom[j] += abs(w)
        mask = denom > 1e-12
        if mask.any():
            new_init[mask] = accum[mask] / denom[mask].unsqueeze(1)
        logger.info(f"New embedding graph-neighbor initialization: {int(mask.sum())}/{n_all - n_old} new nodes matched old neighbors")

    std = old_weight.std(dim=0, keepdim=True).clamp(min=1e-6)
    new_init = new_init + torch.randn_like(new_init) * std * noise_scale
    return new_init


# -----------------------------------------------------------------------------
# Lightning module
# -----------------------------------------------------------------------------


class TraitBulkDeepTAN(LightningModule):
    def __init__(self, pretrained_model, meta: Dict[str, Any], seed_dir: str, cfg: Dict[str, Any]):
        super().__init__()
        self.save_hyperparameters(ignore=["pretrained_model"])
        self.cfg = cfg
        self.loss_cfg = cfg["loss"]
        self.stage_cfg = cfg["stages"]
        self.task_balance_cfg = cfg.get("task_balance", {})

        # Reuse core modules.
        self.amsgp = pretrained_model.amsgp
        self.ge_decoder = pretrained_model.ge_decoder
        self.g_label_predictor = pretrained_model.g_label_predictor

        self.dict_node_names: Dict[str, int] = dict(meta["dict_node_names"])
        self.old_dict_node_names: Dict[str, int] = dict(meta["old_dict_node_names"])
        self.num_old_nodes = int(meta["num_old_nodes"])
        self.num_all_nodes = len(self.dict_node_names)
        self.all_node_names = [None] * self.num_all_nodes
        for n, i in self.dict_node_names.items():
            self.all_node_names[int(i)] = n
        self.input_dim = int(meta.get("input_dim", 1))
        self.is_regression = True
        self.label_mean = float(meta.get("label_mean", 0.0))
        self.label_std = float(meta.get("label_std", 1.0))

        # These attributes are consumed by _install_embedding_grad_hook().
        # They must be initialized before the hook is registered.
        self._stage_old_scale = float(self.stage_cfg.get("old_embedding_scale_stage1", 0.0))
        self._stage_new_scale = float(self.stage_cfg.get("new_embedding_scale_stage1", 1.0))

        self._expand_embedding(pretrained_model, meta, seed_dir)
        self._adapt_trait_predictor()
        self._install_embedding_grad_hook()
        self._register_anchors()

        # Label regression metric buffers.
        # These store graph-level FT16 predictions and true labels.
        self._preds: Dict[str, List[float]] = defaultdict(list)
        self._targets: Dict[str, List[float]] = defaultdict(list)

        # Reconstruction metric buffers.
        # These store node-level reconstructed expression values and true GData.x values
        # for the observed nodes used in the reconstruction loss.
        self._recon_preds: Dict[str, List[float]] = defaultdict(list)
        self._recon_targets: Dict[str, List[float]] = defaultdict(list)

        self._obs: Dict[str, List[str]] = defaultdict(list)
        self.float()

    def _expand_embedding(self, pretrained_model, meta: Dict[str, Any], seed_dir: str):
        node_emb_layer = self.amsgp.node_embedding_layers
        old_embed = node_emb_layer.embed
        old_weight = old_embed.weight.detach().clone()
        if old_weight.shape[0] != self.num_old_nodes:
            raise ValueError(f"Pretrained embed rows {old_weight.shape[0]} != meta num_old_nodes {self.num_old_nodes}")

        new_embed = nn.Embedding(self.num_all_nodes, old_weight.shape[1])
        with torch.no_grad():
            new_embed.weight[: self.num_old_nodes].copy_(old_weight)
            if self.num_all_nodes > self.num_old_nodes:
                init_new = initialize_new_embeddings_from_edges(old_weight, meta, seed_dir)
                new_embed.weight[self.num_old_nodes :].copy_(init_new)
        node_emb_layer.embed = new_embed
        node_emb_layer.dict_node_names = self.dict_node_names
        self.amsgp.dict_node_names = self.dict_node_names
        self.register_buffer("old_embedding_anchor", old_weight, persistent=True)
        self.register_buffer("new_embedding_init", new_embed.weight.detach().clone()[self.num_old_nodes :], persistent=True)
        logger.info(f"Expanded embedding: {old_weight.shape[0]} → {self.num_all_nodes} rows, dim={old_weight.shape[1]}")

    def _adapt_trait_predictor(self):
        name, old_linear = find_last_linear(self.g_label_predictor)
        new_linear = nn.Linear(old_linear.in_features, 1, bias=old_linear.bias is not None)
        nn.init.xavier_uniform_(new_linear.weight)
        if new_linear.bias is not None:
            nn.init.zeros_(new_linear.bias)
        set_submodule(self.g_label_predictor, name, new_linear)
        self._rebuilt_predictor_params = {f"g_label_predictor.{name}.weight"}
        if new_linear.bias is not None:
            self._rebuilt_predictor_params.add(f"g_label_predictor.{name}.bias")
        logger.info(f"Trait predictor rebuilt: Linear({old_linear.in_features}, 1) at g_label_predictor.{name}")

    def _install_embedding_grad_hook(self):
        n_all = self.num_all_nodes
        n_old = self.num_old_nodes
        scale = torch.ones(n_all, 1, dtype=torch.float32)
        scale[:n_old] = self._stage_old_scale
        scale[n_old:] = self._stage_new_scale
        self.register_buffer("embedding_grad_scale", scale, persistent=False)

        def hook(grad):
            return grad * self.embedding_grad_scale.to(grad.device)

        self.amsgp.node_embedding_layers.embed.weight.register_hook(hook)

    def _register_anchors(self):
        self._anchor_param_names: List[Tuple[str, str]] = []
        for name, p in self.named_parameters():
            if not p.requires_grad:
                continue
            if name == "amsgp.node_embedding_layers.embed.weight":
                continue
            if name in getattr(self, "_rebuilt_predictor_params", set()):
                continue
            bname = "_anchor_" + name.replace(".", "__")
            self.register_buffer(bname, p.detach().clone(), persistent=True)
            self._anchor_param_names.append((name, bname))
        logger.info(f"Registered parameter anchors: {len(self._anchor_param_names)} tensors")

    def on_train_epoch_start(self):
        if self.current_epoch < int(self.stage_cfg.get("new_assimilation_epochs", 3)):
            old_scale = float(self.stage_cfg.get("old_embedding_scale_stage1", 0.0))
            new_scale = float(self.stage_cfg.get("new_embedding_scale_stage1", 1.0))
            phase = "STAGE1_NEW_ASSIMILATION"
        else:
            old_scale = float(self.stage_cfg.get("old_embedding_scale_after", 0.03))
            new_scale = float(self.stage_cfg.get("new_embedding_scale_after", 1.0))
            phase = "STAGE2_TRAIT_ADAPTATION"
        self.embedding_grad_scale[: self.num_old_nodes] = old_scale
        self.embedding_grad_scale[self.num_old_nodes :] = new_scale
        task_phase, reg_w, recon_w = self._get_task_weights()
        logger.info(
            f"Epoch {self.current_epoch}: {phase}, "
            f"task_phase={task_phase.upper()}, task_reg_weight={reg_w}, task_recon_weight={recon_w}, "
            f"old_embed_grad_scale={old_scale}, new_embed_grad_scale={new_scale}"
        )

    def forward(self, batch: GData, compute_recon: bool = True) -> Dict[str, Optional[torch.Tensor]]:
        """Run DeepTAN forward pass.

        Parameters
        ----------
        compute_recon
            If False, skip ``ge_decoder`` and reconstruction masks.  This is the
            key speed optimization for regress-only phases and FT16-only
            validation/test/predict.  ``amsgp`` and ``g_label_predictor`` are
            still evaluated, so regression metrics are unchanged.
        """
        node_batch = getattr(batch, "batch", torch.zeros(batch.x.size(0), dtype=torch.long, device=self.device))
        if batch.x.dtype != torch.float32:
            batch.x = batch.x.float()
        if batch.edge_index.dtype != torch.long:
            batch.edge_index = batch.edge_index.long()

        z, ids = self.amsgp(
            node_names=batch.node_names,
            x=batch.x,
            edge_index=batch.edge_index,
            batch=node_batch,
        )
        trait_pred = self.g_label_predictor(z).view(-1)

        if compute_recon:
            recon_node_emb, pred_feat_values = self.ge_decoder(z, self.amsgp.node_embedding_layers.embed.weight)
            pred_nonzero, pred_zeros, valid_ids = self._create_node_masks_aligned(batch.node_names, pred_feat_values, ids)
        else:
            recon_node_emb = None
            pred_feat_values = None
            pred_nonzero = None
            pred_zeros = None
            valid_ids = ids.clone()

        return {
            "embedding": z,
            "node_recon": recon_node_emb,
            "node_recon_all": pred_feat_values,
            "trait_pred": trait_pred,
            "pred_nonzero": pred_nonzero,
            "pred_zeros": pred_zeros,
            "valid_node_ids": valid_ids,
            "compute_recon": torch.tensor(bool(compute_recon), device=z.device),
        }

    def _create_node_masks_aligned(self, batch_node_names, pred_feat_values: torch.Tensor, ids: torch.Tensor):
        counts = [len(nodes) for nodes in batch_node_names]
        cum = [0]
        for c in counts:
            cum.append(cum[-1] + c)
        B, N_all = pred_feat_values.shape[0], pred_feat_values.shape[1]
        if pred_feat_values.dim() == 3 and pred_feat_values.shape[2] == 1:
            pred_2d = pred_feat_values.squeeze(2)
        elif pred_feat_values.dim() == 3:
            pred_2d = pred_feat_values.flatten(1)
        else:
            pred_2d = pred_feat_values
        valid = []
        mask = torch.zeros(B, N_all, dtype=torch.bool, device=pred_feat_values.device)
        for i in range(B):
            idx = ids[cum[i] : cum[i + 1]]
            valid.append(pred_2d[i, idx])
            mask[i, idx] = True
        pred_nonzero = torch.cat(valid, dim=0) if valid else torch.empty(0, device=pred_feat_values.device)
        pred_zeros = pred_2d[~mask]
        return pred_nonzero, pred_zeros, ids.clone()

    def _get_task_phase(self) -> str:
        r"""Return the current epoch-level task phase.

        This implements DeepTAN-style task alternation for fair comparison with
        bulk-from-scratch DeepTAN while keeping the transfer-stability regularizers
        available in all phases.
        """
        tb = self.task_balance_cfg or {}
        strategy = str(tb.get("strategy", "cycle")).lower()
        if strategy == "joint":
            return "joint"
        if strategy != "cycle":
            raise ValueError(f"Unsupported task_balance.strategy={strategy!r}; expected 'cycle' or 'joint'.")

        warmup = int(tb.get("warmup_recon_epochs", 3))
        if self.current_epoch < warmup:
            return "recon"

        cycle = list(tb.get("cycle", ["recon", "regress", "joint"]))
        if not cycle:
            raise ValueError("task_balance.cycle must contain at least one phase")
        phase = str(cycle[(self.current_epoch - warmup) % len(cycle)]).lower()
        if phase not in {"recon", "regress", "joint"}:
            raise ValueError(f"Invalid task phase {phase!r}; expected recon/regress/joint")
        return phase

    def _get_task_weights(self) -> Tuple[str, float, float]:
        tb = self.task_balance_cfg or {}
        phase = self._get_task_phase()
        if phase == "recon":
            reg_w = float(tb.get("recon_focus_reg_weight", 0.0))
            recon_w = float(tb.get("recon_focus_recon_weight", 1.0))
        elif phase == "regress":
            reg_w = float(tb.get("regress_focus_reg_weight", 1.0))
            recon_w = float(tb.get("regress_focus_recon_weight", 0.0))
        else:
            reg_w = float(tb.get("joint_reg_weight", 1.0))
            recon_w = float(tb.get("joint_recon_weight", 1.0))
        return phase, reg_w, recon_w

    def _get_stage_task_weights(self, stage: str) -> Tuple[str, float, float]:
        """Return phase and task weights for train/val/test.

        Training uses the configured DeepTAN-style cycle.  Validation/test are
        FT16-regression diagnostics by default, so they skip reconstruction
        unless ``eval_compute_recon=True`` is set in the config.
        """
        if stage == "train":
            return self._get_task_weights()
        if bool(self.cfg.get("eval_compute_recon", False)):
            return "eval_joint", 1.0, 1.0
        return "eval_regress", 1.0, 0.0

    def _needs_decoder(self, stage: str) -> bool:
        """Whether this step needs GE decoder outputs."""
        _phase, _reg_w, recon_w = self._get_stage_task_weights(stage)
        zero_active = bool(self.loss_cfg.get("use_zero_penalty", False)) and float(self.loss_cfg.get("lambda_zero", 0.0)) > 0.0
        skip_when_unused = bool(self.cfg.get("skip_decoder_when_unused", True))
        if not skip_when_unused:
            return True
        return (recon_w > 0.0) or zero_active

    def _compute_losses(self, outputs: Dict[str, Optional[torch.Tensor]], batch: GData, stage: str) -> Dict[str, torch.Tensor]:
        y = batch.y.view(-1).float()
        pred = outputs["trait_pred"].view(-1)  # type: ignore[union-attr]
        losses: Dict[str, torch.Tensor] = {}
        # Internal optimization loss on the normalized training label scale.
        # It is intentionally prefixed with '_' so it is not logged as a public metric.
        # Public label-regression metrics are logged later as label_regression_MSE/MAE/PCC/RMSE
        # on the original FT16 scale.
        losses["_label_regression_MSE_train_scale"] = F.mse_loss(pred, y)

        phase, task_reg_weight, task_recon_weight = self._get_stage_task_weights(stage)
        device = pred.device
        losses["task_reg_weight"] = torch.tensor(task_reg_weight, dtype=torch.float32, device=device)
        losses["task_recon_weight"] = torch.tensor(task_recon_weight, dtype=torch.float32, device=device)

        pred_nonzero = outputs.get("pred_nonzero")
        pred_zeros = outputs.get("pred_zeros")
        if pred_nonzero is not None:
            target = batch.x.squeeze(-1).float()
            losses["_recon_MSE_loss"] = F.mse_loss(pred_nonzero.view_as(target), target)
        else:
            # Decoder was intentionally skipped for regress-only phases/evaluation.
            losses["_recon_MSE_loss"] = torch.tensor(0.0, device=device)
            if task_recon_weight > 0.0:
                raise RuntimeError(
                    f"Internal error: phase={phase!r} requires reconstruction loss, "
                    "but GE decoder outputs were not computed."
                )

        losses["param_anchor_L2"] = self._parameter_anchor_loss()
        losses["old_embedding_anchor_MSE"] = F.mse_loss(
            self.amsgp.node_embedding_layers.embed.weight[: self.num_old_nodes], self.old_embedding_anchor
        )
        if self.num_all_nodes > self.num_old_nodes:
            losses["new_smoothness_MSE"] = F.mse_loss(
                self.amsgp.node_embedding_layers.embed.weight[self.num_old_nodes :], self.new_embedding_init
            )
        else:
            losses["new_smoothness_MSE"] = torch.tensor(0.0, device=device)

        if bool(self.loss_cfg.get("use_zero_penalty", False)) and pred_zeros is not None and pred_zeros.numel() > 0:
            losses["zero_MSE"] = F.mse_loss(pred_zeros, torch.zeros_like(pred_zeros))
        else:
            losses["zero_MSE"] = torch.tensor(0.0, device=device)

        # Main task terms are alternated at the epoch level. Transfer-stability
        # regularizers remain active by default, because they are not separate
        # biological tasks; they stabilize pretrained-to-bulk adaptation.
        main_loss = (
            task_reg_weight * float(self.loss_cfg.get("lambda_reg", 1.0)) * losses["_label_regression_MSE_train_scale"]
            + task_recon_weight * float(self.loss_cfg.get("lambda_recon", 0.2)) * losses["_recon_MSE_loss"]
        )

        if bool((self.task_balance_cfg or {}).get("regularization_in_all_phases", True)):
            reg_loss = (
                float(self.loss_cfg.get("lambda_anchor", 0.02)) * losses["param_anchor_L2"]
                + float(self.loss_cfg.get("lambda_old_embedding_anchor", 0.02)) * losses["old_embedding_anchor_MSE"]
                + float(self.loss_cfg.get("lambda_new_smoothness", 0.01)) * losses["new_smoothness_MSE"]
                + float(self.loss_cfg.get("lambda_zero", 0.0)) * losses["zero_MSE"]
            )
        else:
            reg_loss = torch.tensor(0.0, device=device)

        losses["task_main_loss"] = main_loss
        losses["regularization_loss"] = reg_loss
        losses["loss"] = main_loss + reg_loss
        return losses

    def _parameter_anchor_loss(self) -> torch.Tensor:
        if self.current_epoch < int(self.cfg.get("warmup_epochs", 3)):
            return torch.tensor(0.0, device=self.device)
        loss = torch.tensor(0.0, device=self.device)
        n = 0
        for name, bname in self._anchor_param_names:
            obj: Any = self
            ok = True
            for part in name.split("."):
                if not hasattr(obj, part):
                    ok = False
                    break
                obj = getattr(obj, part)
            if not ok or not isinstance(obj, torch.Tensor):
                continue
            anchor = getattr(self, bname)
            loss = loss + torch.sum((obj - anchor) ** 2)
            n += obj.numel()
        return loss / max(n, 1)

    def _shared_step(self, batch: GData, stage: str) -> torch.Tensor:
        compute_recon = self._needs_decoder(stage)
        out = self(batch, compute_recon=compute_recon)
        losses = self._compute_losses(out, batch, stage=stage)
        for k, v in losses.items():
            # Internal train-scale losses are used only to build the objective;
            # do not expose them in Lightning tables to avoid confusion with
            # final comparable metrics.
            if k.startswith("_"):
                continue
            self.log(
                f"{stage}/{k}",
                v,
                prog_bar=(k == "loss"),
                on_step=(stage == "train"),
                on_epoch=True,
                batch_size=getattr(batch, "num_graphs", 1),
                sync_dist=True,
            )
        # Filename-safe alias for the validation objective used by ModelCheckpoint.
        # The canonical metric remains ``val/loss``; ``val_loss`` is only used in checkpoint filenames.
        if stage == "val":
            self.log(
                "val_loss",
                losses["loss"],
                prog_bar=False,
                on_step=False,
                on_epoch=True,
                batch_size=getattr(batch, "num_graphs", 1),
                sync_dist=True,
            )
        phase, _, _ = self._get_stage_task_weights(stage)
        phase_id = {"recon": 0.0, "regress": 1.0, "joint": 2.0, "eval_regress": 3.0, "eval_joint": 4.0}[phase]
        self.log(
            f"{stage}/task_phase_id",
            torch.tensor(phase_id, device=self.device),
            prog_bar=False,
            on_step=False,
            on_epoch=True,
            batch_size=getattr(batch, "num_graphs", 1),
            sync_dist=True,
        )
        self.log(
            f"{stage}/decoder_computed",
            torch.tensor(float(compute_recon), device=self.device),
            prog_bar=False,
            on_step=(stage == "train"),
            on_epoch=True,
            batch_size=getattr(batch, "num_graphs", 1),
            sync_dist=True,
        )
        pred_raw = (out["trait_pred"].detach().cpu().numpy() * self.label_std + self.label_mean).tolist()  # type: ignore[union-attr]
        y_raw = (batch.y.detach().view(-1).cpu().numpy() * self.label_std + self.label_mean).tolist()
        self._preds[stage].extend(pred_raw)
        self._targets[stage].extend(y_raw)
        if hasattr(batch, "obs_name"):
            obs = batch.obs_name if isinstance(batch.obs_name, list) else [str(batch.obs_name)]
            self._obs[stage].extend(obs)

        # Reconstruction task metrics: node-level reconstruction prediction vs true node value.
        # This is separate from label regression metrics above.
        pred_nonzero = out.get("pred_nonzero")
        if pred_nonzero is not None:
            recon_pred = pred_nonzero.detach().view(-1).cpu().numpy().tolist()
            recon_true = batch.x.detach().squeeze(-1).view(-1).cpu().numpy().tolist()
            self._recon_preds[stage].extend(recon_pred)
            self._recon_targets[stage].extend(recon_true)

        return losses["loss"]

    def training_step(self, batch: GData, batch_idx: int):
        return self._shared_step(batch, "train")

    def validation_step(self, batch: GData, batch_idx: int):
        return self._shared_step(batch, "val")

    def test_step(self, batch: GData, batch_idx: int):
        return self._shared_step(batch, "test")

    def predict_step(self, batch: GData, batch_idx: int):
        # Final prediction/export step.
        # We compute both tasks here so that output files can clearly separate:
        #   1) label_regression: graph-level FT16_pred vs FT16_true
        #   2) reconstruction: node-level reconstructed x vs true x
        out = self(batch, compute_recon=True)

        # Label regression outputs are reported on the original FT16 scale.
        pred_raw = out["trait_pred"] * self.label_std + self.label_mean
        y_raw = batch.y.view(-1) * self.label_std + self.label_mean

        result = {
            # Backward-compatible names used by older code.
            "pred": pred_raw.detach().cpu(),
            "target": y_raw.detach().cpu(),
            # Explicit task-specific names.
            "label_regression_pred": pred_raw.detach().cpu(),
            "label_regression_target": y_raw.detach().cpu(),
            "obs_name": batch.obs_name,
        }

        pred_nonzero = out.get("pred_nonzero")
        if pred_nonzero is not None:
            result["reconstruction_pred"] = pred_nonzero.detach().view(-1).cpu()
            result["reconstruction_target"] = batch.x.detach().squeeze(-1).view(-1).cpu()

        return result

    def on_train_epoch_end(self):
        self._log_epoch_metrics("train")

    def on_validation_epoch_end(self):
        self._log_epoch_metrics("val")

    def on_test_epoch_end(self):
        self._log_epoch_metrics("test")

    def _log_epoch_metrics(self, stage: str):
        # ------------------------------------------------------------------
        # Label regression metrics: graph-level FT16_pred vs FT16_true.
        # Public names intentionally match the bulk-from-scratch DeepTAN style:
        #   {stage}/label_regression_MSE
        #   {stage}/label_regression_MAE
        #   {stage}/label_regression_PCC
        #   {stage}/label_regression_RMSE
        # ------------------------------------------------------------------
        if self._targets[stage]:
            label_metrics = named_regression_metrics(np.array(self._targets[stage]), np.array(self._preds[stage]))
            for k, v in label_metrics.items():
                if np.isfinite(v):
                    self.log(
                        f"{stage}/label_regression_{k}",
                        float(v),
                        prog_bar=(stage == "val" and k in {"PCC", "RMSE"}),
                        sync_dist=True,
                    )

        # ------------------------------------------------------------------
        # Reconstruction metrics: node-level reconstructed x vs true GData.x.
        # Public names intentionally match the bulk-from-scratch DeepTAN style:
        #   {stage}/recon_MSE
        #   {stage}/recon_MAE
        #   {stage}/recon_PCC
        #   {stage}/recon_RMSE
        # ------------------------------------------------------------------
        if self._recon_targets[stage]:
            recon_metrics = named_regression_metrics(np.array(self._recon_targets[stage]), np.array(self._recon_preds[stage]))
            for k, v in recon_metrics.items():
                if np.isfinite(v):
                    self.log(f"{stage}/recon_{k}", float(v), sync_dist=True)

        self._preds[stage].clear()
        self._targets[stage].clear()
        self._recon_preds[stage].clear()
        self._recon_targets[stage].clear()
        self._obs[stage].clear()

    def configure_optimizers(self):
        m = self.cfg["lr_multipliers"]
        base = float(self.cfg["base_lr"])
        node = self.amsgp.node_embedding_layers
        groups = [
            {"params": list(node.embed.parameters()), "lr": base, "name": "embedding_row_scaled"},
            {"params": list(node.feature_proj.parameters()), "lr": base * float(m["feature_proj"]), "name": "feature_proj"},
            {"params": list(node.fusion_mlp.parameters()), "lr": base * float(m["fusion_mlp"]), "name": "fusion_mlp"},
            {"params": list(node._layers.parameters()) + list(node.norm.parameters()), "lr": base * float(m["gat_layers"]), "name": "gat_layers"},
            {"params": list(self.amsgp.sagpool1.parameters()) + list(self.amsgp.global_xgat_pool1.parameters()) + list(self.amsgp.global_sagpool1.parameters()), "lr": base * float(m["pooling"]), "name": "pooling"},
            {"params": list(self.ge_decoder.parameters()), "lr": base * float(m["ge_decoder"]), "name": "ge_decoder"},
            {"params": list(self.g_label_predictor.parameters()), "lr": base * float(m["trait_predictor"]), "name": "trait_predictor"},
        ]
        for g in groups:
            n_train = sum(p.numel() for p in g["params"] if p.requires_grad)
            logger.info(f"Param group {g['name']}: lr={g['lr']:.2e}, trainable={n_train:,}")
        opt = AdamW(groups, weight_decay=float(self.cfg["weight_decay"]), betas=(0.9, 0.999), eps=1e-8)
        if self.cfg.get("scheduler") == "plateau":
            sch = torch.optim.lr_scheduler.ReduceLROnPlateau(opt, mode="min", factor=float(self.cfg["plateau_factor"]), patience=int(self.cfg["plateau_patience"]), min_lr=float(self.cfg["min_lr"]))
            return {"optimizer": opt, "lr_scheduler": {"scheduler": sch, "monitor": "val/loss", "interval": "epoch", "frequency": 1}}
        sch = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(opt, T_0=int(self.cfg["cosine_T0"]), T_mult=int(self.cfg["cosine_T_mult"]), eta_min=float(self.cfg["min_lr"]))
        return {"optimizer": opt, "lr_scheduler": {"scheduler": sch, "interval": "epoch", "frequency": 1}}


# -----------------------------------------------------------------------------
# Training orchestration
# -----------------------------------------------------------------------------


def _is_litdata_dir(path: str) -> bool:
    return (
        os.path.isdir(path)
        and os.path.isfile(os.path.join(path, "expanded_metadata.pkl"))
        and os.path.isdir(os.path.join(path, "trn"))
        and os.path.isdir(os.path.join(path, "val"))
        and os.path.isdir(os.path.join(path, "tst"))
    )


def resolve_litdata_dir(cfg: Dict[str, Any]) -> Tuple[str, str]:
    """Resolve the LitData directory for the single-run workflow.

    Preferred GitHub-facing layout:
        dataset_root/expanded_metadata.pkl
        dataset_root/trn
        dataset_root/val
        dataset_root/tst

    Backward-compatible legacy layout:
        dataset_root/seed_<data_id>/expanded_metadata.pkl
        dataset_root/seed_<data_id>/trn
        dataset_root/seed_<data_id>/val
        dataset_root/seed_<data_id>/tst
    """
    root = str(cfg.get("dataset_root", "") or "")
    if not root:
        raise ValueError("Config field dataset_root is required.")

    data_id = str(cfg.get("data_id", "bulk_run") or "bulk_run")

    if _is_litdata_dir(root):
        return root, data_id

    candidates: List[Tuple[str, str]] = []
    if data_id:
        candidates.append((os.path.join(root, f"seed_{data_id}"), data_id))

    legacy_seeds = list(cfg.get("seeds", []) or [])
    if legacy_seeds:
        sid = str(legacy_seeds[0])
        candidates.append((os.path.join(root, f"seed_{sid}"), sid))

    for candidate, cid in candidates:
        if _is_litdata_dir(candidate):
            logger.warning(
                f"Using legacy LitData subdirectory layout: {candidate}. "
                "For the single-run GitHub workflow, prefer setting dataset_root directly to the directory "
                "that contains trn/val/tst and expanded_metadata.pkl."
            )
            return candidate, cid

    expected = (
        f"Expected either {root}/trn, {root}/val, {root}/tst, {root}/expanded_metadata.pkl "
        "or a legacy dataset_root/seed_<data_id> directory with those files."
    )
    raise FileNotFoundError(expected)


def make_dataloader(seed_dir: str, split: str, cfg: Dict[str, Any]):
    ds = litdata.StreamingDataset(os.path.join(seed_dir, split), max_cache_size="10GB")
    return litdata.StreamingDataLoader(
        ds,
        batch_size=int(cfg["batch_size"]),
        num_workers=int(cfg.get("n_workers", 4)),
        collate_fn=collate_fn,
    )


def run_single_dataset(cfg: Dict[str, Any]) -> Dict[str, float]:
    dataset_dir, data_id = resolve_litdata_dir(cfg)
    meta_path = os.path.join(dataset_dir, "expanded_metadata.pkl")
    with open(meta_path, "rb") as f:
        meta = pickle.load(f)

    pretrained = load_pretrained_model(cfg["pretrained_ckpt"])
    model = TraitBulkDeepTAN(pretrained, meta, dataset_dir, cfg)

    train_loader = make_dataloader(dataset_dir, "trn", cfg)
    val_loader = make_dataloader(dataset_dir, "val", cfg)
    test_loader = make_dataloader(dataset_dir, "tst", cfg)

    out_dir = str(cfg["output_dir"])
    os.makedirs(out_dir, exist_ok=True)
    logger_tb = TensorBoardLogger(save_dir=out_dir, name="tensorboard")

    safe_data_id = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(data_id))
    ckpt_prefix = f"FT16_{safe_data_id}_"
    ckpt = ModelCheckpoint(
        dirpath=out_dir,
        filename=ckpt_prefix + "epoch={epoch:02d}_val_loss={val_loss:.4f}",
        monitor="val/loss",
        mode="min",
        save_top_k=3,
        save_last=False,
        auto_insert_metric_name=False,
    )
    early = EarlyStopping(monitor="val/loss", mode="min", patience=int(cfg["es_patience"]), min_delta=1e-4)
    trainer = Trainer(
        accelerator=cfg["accelerator"],
        devices=cfg["devices"],
        precision=cfg["precision"],
        max_epochs=int(cfg["max_epochs"]),
        min_epochs=int(cfg["min_epochs"]),
        accumulate_grad_batches=int(cfg["accumulate_grad_batches"]),
        gradient_clip_val=float(cfg["gradient_clip_val"]),
        logger=logger_tb,
        callbacks=[ckpt, early, LearningRateMonitor(logging_interval="epoch")],
        log_every_n_steps=10,
        num_sanity_val_steps=int(cfg.get("num_sanity_val_steps", 0)),
        check_val_every_n_epoch=int(cfg.get("check_val_every_n_epoch", 1)),
    )
    trainer.fit(model, train_loader, val_loader)
    best_path = ckpt.best_model_path
    best_score = ckpt.best_model_score
    if not best_path:
        raise RuntimeError(
            "No checkpoint was saved. Check whether validation ran and whether val/loss was logged."
        )
    logger.info(f"Best checkpoint: {best_path}")

    test_result = trainer.test(model, dataloaders=test_loader, ckpt_path=best_path)

    metadata = {
        "task": "Trait-aware BulkExpand-DeepTAN fine-tuning",
        "data_id": data_id,
        "training_seed": int(cfg.get("seed", 42)),
        "dataset_dir": dataset_dir,
        "output_dir": out_dir,
        "best_ckpt": best_path,
        "best_val_loss": float(best_score.item()) if best_score is not None else None,
        "monitor": "val/loss",
        "mode": "min",
        "save_top_k": 3,
        "checkpoint_pattern": ckpt_prefix + "epoch={epoch:02d}_val_loss={val_loss:.4f}.ckpt",
        "pretrained_ckpt": cfg["pretrained_ckpt"],
        "dataset_root": cfg["dataset_root"],
        "test_result": test_result,
        "config": cfg,
    }
    with open(os.path.join(out_dir, "finetune_metadata.pkl"), "wb") as f:
        pickle.dump(metadata, f)

    preds = trainer.predict(model, dataloaders=test_loader, ckpt_path=best_path)

    pred_list, target_list, obs_list = [], [], []
    recon_pred_list, recon_target_list = [], []

    for batch in preds:
        pred_list.extend(batch["label_regression_pred"].numpy().tolist())
        target_list.extend(batch["label_regression_target"].numpy().tolist())
        obs = batch.get("obs_name", [])
        if isinstance(obs, list):
            obs_list.extend([str(x) for x in obs])

        if "reconstruction_pred" in batch and "reconstruction_target" in batch:
            recon_pred_list.extend(batch["reconstruction_pred"].numpy().tolist())
            recon_target_list.extend(batch["reconstruction_target"].numpy().tolist())

    label_metrics = named_regression_metrics(np.array(target_list), np.array(pred_list))
    reconstruction_metrics = (
        named_regression_metrics(np.array(recon_target_list), np.array(recon_pred_list))
        if len(recon_target_list) > 0
        else None
    )

    metrics_payload = {
        "data_id": data_id,
        "training_seed": int(cfg.get("seed", 42)),
        "notes": {
            "label_regression": "FT16 label regression metrics: FT16_pred vs FT16_true on the original label scale.",
            "recon": "Node-level reconstruction metrics: reconstructed observed node x vs true GData.x on the model input expression scale.",
            "PCC": "PCC is the Pearson correlation coefficient.",
            "removed": "Internal train-scale losses such as label_regression_MSE_train_scale are not logged or exported as public metrics.",
        },
        "label_regression": label_metrics,
        "recon": reconstruction_metrics,
    }

    flat_metrics: Dict[str, float] = {}
    flat_metrics.update(flatten_metrics("label_regression", label_metrics))
    flat_metrics.update(flatten_metrics("recon", reconstruction_metrics))

    pl.DataFrame({"obs_name": obs_list, "FT16_true": target_list, "FT16_pred": pred_list}).write_csv(
        os.path.join(out_dir, "test_label_regression_predictions.csv")
    )
    pl.DataFrame({"obs_name": obs_list, "FT16_true": target_list, "FT16_pred": pred_list}).write_csv(
        os.path.join(out_dir, "test_predictions.csv")
    )

    with open(os.path.join(out_dir, "test_label_regression_metrics.json"), "w") as f:
        json.dump({"data_id": data_id, "task": "label_regression", "metrics": label_metrics}, f, indent=2)

    if reconstruction_metrics is not None:
        with open(os.path.join(out_dir, "test_recon_metrics.json"), "w") as f:
            json.dump({"data_id": data_id, "task": "recon", "metrics": reconstruction_metrics}, f, indent=2)
        with open(os.path.join(out_dir, "test_reconstruction_metrics.json"), "w") as f:
            json.dump({"data_id": data_id, "task": "recon", "metrics": reconstruction_metrics}, f, indent=2)

    with open(os.path.join(out_dir, "test_metrics.json"), "w") as f:
        json.dump(metrics_payload, f, indent=2)

    return flat_metrics



def main():
    parser = argparse.ArgumentParser(description="Run02: fine-tune scRNA-pretrained DeepTAN on one trait-aware bulk LitData directory.")
    parser.add_argument("--config", required=True, help="YAML fine-tuning config path")
    parser.add_argument("--dataset_root", default=None, help="Override config.dataset_root. Should directly contain trn/val/tst and expanded_metadata.pkl.")
    parser.add_argument("--output_dir", default=None, help="Override config.output_dir")
    parser.add_argument("--data_id", default=None, help="Optional human-readable identifier for this run")
    parser.add_argument("--training_seed", type=int, default=None, help="Override config.seed, the training random seed")
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Deprecated legacy alias for --data_id when reading dataset_root/seed_<seed>. Do not use for the single-run workflow.",
    )
    args = parser.parse_args()

    cfg = load_config(args.config)
    if args.dataset_root:
        cfg["dataset_root"] = args.dataset_root
    if args.output_dir:
        cfg["output_dir"] = args.output_dir
    if args.data_id:
        cfg["data_id"] = str(args.data_id)
    elif args.seed is not None:
        cfg["data_id"] = str(args.seed)
    if args.training_seed is not None:
        cfg["seed"] = int(args.training_seed)

    setup_deeptan_path(cfg["local_deeptan_src"])
    os.makedirs(cfg["output_dir"], exist_ok=True)
    seed_everything(int(cfg.get("seed", 42)), workers=True)

    logger.info("=" * 80)
    logger.info(
        "Trait-aware BulkExpand-DeepTAN single-run fine-tuning | "
        f"data_id={cfg.get('data_id', 'bulk_run')} | training_seed={cfg.get('seed', 42)}"
    )
    flat_metrics = run_single_dataset(cfg)

    df = pl.DataFrame([{"data_id": str(cfg.get("data_id", "bulk_run")), **flat_metrics}])
    df.write_csv(os.path.join(cfg["output_dir"], "summary_metrics.csv"))
    summary = {}
    for col in df.columns:
        if col == "data_id":
            continue
        try:
            vals = df[col].to_numpy().astype(float)
        except Exception:
            continue
        summary[col] = {
            "mean": float(np.nanmean(vals)),
            "std": 0.0,
        }
    with open(os.path.join(cfg["output_dir"], "summary_metrics_mean_std.json"), "w") as f:
        json.dump(summary, f, indent=2)
    logger.success(f"All done. Summary saved to {cfg['output_dir']}")


if __name__ == "__main__":
    main()
