#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
==============================================================================
Run04: Trait-Aware Bulk Network Downstream 
==============================================================================

Purpose
-------
Run non-plotting downstream  for one trait-aware bulk latent network
extracted by Run03.

Pipeline position
-----------------
Run01: user-defined raw bulk files -> LitData
Run02: LitData -> fine-tuned BulkExpand-DeepTAN checkpoint
Run03: LitData + fine-tuned checkpoint -> trait-aware latent network
Run04: trait-aware latent network -> module / hub / gene-set 

Core  workflow
----------------------
This script performs table-based downstream  only. It does not retrain
the model, re-extract node embeddings, or draw publication figures.

Main steps:
  1. Read the Run03 edge table, usually bulk_trait_edge_table.parquet.
  2. Use abs(weight_col), default abs(w_ft), as the non-negative edge strength.
  3. Select the edge subset used for module detection.
  4. Build an undirected weighted NetworkX graph.
  5. Detect modules with Leiden, Louvain, or greedy modularity fallback.
  6. Merge very small raw communities into the largest retained module.
  7. Identify module hub genes by intra-module weighted degree.
  8. Export module-level gene sets and hub-gene sets for external enrichment.
  9. Save stable analysis tables for downstream biological interpretation and
     optional external visualization.

Recommended usage
-----------------
Using the directory generated by Run03:

    python bulk_network_downstream_analysis.py \
        --network_dir /path/to/network_output/trait_network \
        --out_dir /path/to/downstream_output

Equivalent explicit edge-table mode:

    python bulk_network_downstream_analysis.py \
        --edge_table /path/to/network_output/trait_network/bulk_trait_edge_table.parquet \
        --out_dir /path/to/downstream_output

Output
------
The script creates:

    out_dir/
        tables/
            analysis_edge_table.parquet
            analysis_metadata.yaml
            module_assignment.csv
            module_summary.csv
            module_count_summary.csv
            hub_gene_summary.csv
            module_edges.parquet
        gene_sets/
            module_genes/
            module_hubs/

Notes
-----
The --seed argument controls reproducibility for stochastic community-detection
backends. It is not a bulk data split identifier.

Author: DeepTAN Bulk Downstream Analysis Pipeline
"""

from __future__ import annotations

import argparse
import math
import os
import random
import warnings
from collections import defaultdict
from typing import Dict, Iterable, List, Optional, Tuple

import networkx as nx
import numpy as np
import polars as pl
import yaml

warnings.filterwarnings("ignore", category=FutureWarning)


# =============================================================================
# Basic file and numeric utilities
# =============================================================================

def ensure_dir(path: str) -> str:
    os.makedirs(path, exist_ok=True)
    return path


def write_gene_list(path: str, genes: Iterable[str]) -> None:
    with open(path, "w") as f:
        for g in sorted(set(str(x) for x in genes)):
            f.write(g + "\n")


def safe_float(x, default: float = 0.0) -> float:
    try:
        if x is None:
            return default
        v = float(x)
        if not np.isfinite(v):
            return default
        return v
    except Exception:
        return default


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run04: perform non-plotting module, hub and gene-set analysis for one "
            "trait-aware bulk network extracted by Run03."
        )
    )

    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument(
        "--edge_table",
        default=None,
        help="Path to bulk_trait_edge_table.parquet generated by Run03 network extraction.",
    )
    input_group.add_argument(
        "--network_dir",
        default=None,
        help=(
            "Trait network directory generated by Run03 bulk_trait_network_extract_single.py. "
            "It should contain bulk_trait_edge_table.parquet."
        ),
    )

    parser.add_argument(
        "--out_dir",
        required=True,
        help=(
            "Output directory for downstream analysis tables and gene sets. "
            "The script creates tables/ and gene_sets/ under this directory."
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help=(
            "Random seed used for reproducible stochastic community detection. "
            "This is not a bulk data split seed."
        ),
    )

    # Network construction and module detection.
    parser.add_argument("--weight_col", default="w_ft", help="Signed edge-weight column. Edge strength is computed as abs(weight_col). Default: w_ft.")
    parser.add_argument(
        "--module_top_frac",
        type=float,
        default=1.0,
        help="Fraction of strongest edges by abs(weight_col) used for module detection. Default 1.0 uses all non-zero edges.",
    )
    parser.add_argument(
        "--min_abs_weight",
        type=float,
        default=None,
        help="Optional minimum abs(weight_col) for module detection. Default: no threshold.",
    )
    parser.add_argument(
        "--min_weight",
        dest="min_abs_weight",
        type=float,
        default=None,
        help="Alias of --min_abs_weight for backward compatibility.",
    )
    parser.add_argument("--min_module_size", type=int, default=50, help="Raw communities smaller than this size are merged into the largest retained module.")
    parser.add_argument(
        "--resolution",
        type=float,
        default=1.3,
        help="Community-detection resolution for Leiden/Louvain when available.",
    )

    # Hub definition.
    parser.add_argument("--hub_top_frac", type=float, default=0.10, help="Fraction of nodes per module selected as hub genes.")
    parser.add_argument("--min_hubs", type=int, default=1, help="Minimum number of hubs per retained module.")
    parser.add_argument("--max_hubs", type=int, default=100000, help="Maximum number of hubs per module.")

    return parser.parse_args()


# =============================================================================
# Core downstream analysis functions
# =============================================================================

def resolve_edge_table(args: argparse.Namespace) -> str:
    if args.edge_table:
        path = os.path.abspath(os.path.expanduser(args.edge_table))
        if not os.path.exists(path):
            raise FileNotFoundError(f"edge_table not found: {path}")
        return path

    network_dir = os.path.abspath(os.path.expanduser(args.network_dir))
    candidates = [
        os.path.join(network_dir, "bulk_trait_edge_table.parquet"),
        os.path.join(network_dir, "bulk_trait_csn_edge_table.parquet"),
    ]
    for path in candidates:
        if os.path.exists(path):
            return path
    raise FileNotFoundError("No edge table found in network_dir. Tried: " + ", ".join(candidates))


# =============================================================================
# Edge-table loading and graph construction
# =============================================================================


def load_edge_table(edge_table_path: str, weight_col: str) -> pl.DataFrame:
    df = pl.read_parquet(edge_table_path)

    required = ["gene_i_name", "gene_j_name", weight_col]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in edge table: {missing}")

    if "delta_w" not in df.columns:
        df = df.with_columns(pl.lit(None).cast(pl.Float64).alias("delta_w"))
    if "abs_delta_w" not in df.columns:
        df = df.with_columns(pl.col("delta_w").abs().alias("abs_delta_w"))
    if "gene_i_type" not in df.columns:
        df = df.with_columns(pl.lit("unknown").alias("gene_i_type"))
    if "gene_j_type" not in df.columns:
        df = df.with_columns(pl.lit("unknown").alias("gene_j_type"))

    df = df.with_columns(pl.col(weight_col).abs().alias("edge_strength"))
    df = (
        df
        .filter(pl.col("gene_i_name") != pl.col("gene_j_name"))
        .filter(pl.col(weight_col).is_not_null())
        .filter(pl.col("edge_strength").is_not_null())
        .filter(pl.col("edge_strength") > 0)
    )
    if df.height == 0:
        raise ValueError("No non-zero edges remain after loading the edge table.")
    return df


def get_node_type_map(df: pl.DataFrame) -> Dict[str, str]:
    node_type: Dict[str, str] = {}
    for row in df.select(["gene_i_name", "gene_i_type", "gene_j_name", "gene_j_type"]).iter_rows(named=True):
        node_type.setdefault(str(row["gene_i_name"]), str(row.get("gene_i_type", "unknown")))
        node_type.setdefault(str(row["gene_j_name"]), str(row.get("gene_j_type", "unknown")))
    return node_type


def select_module_edges(df: pl.DataFrame, top_frac: float, min_abs_weight: Optional[float]) -> pl.DataFrame:
    d = df
    if min_abs_weight is not None:
        d = d.filter(pl.col("edge_strength") >= float(min_abs_weight))

    if d.height == 0:
        raise ValueError("No edges remain for module detection after filtering.")

    top_frac = float(top_frac)
    if top_frac <= 0 or top_frac > 1:
        raise ValueError("module_top_frac must be in (0, 1].")

    if top_frac < 1.0:
        k = max(1, int(math.ceil(d.height * top_frac)))
        d = d.sort("edge_strength", descending=True).head(k)

    return d


def build_graph_from_edges(df: pl.DataFrame, signed_weight_col: str) -> nx.Graph:
    G = nx.Graph()
    for r in df.iter_rows(named=True):
        u = str(r["gene_i_name"])
        v = str(r["gene_j_name"])
        strength = safe_float(r.get("edge_strength"), 0.0)
        if u == v or strength <= 0:
            continue
        signed_w = safe_float(r.get(signed_weight_col), 0.0)
        delta = safe_float(r.get("delta_w"), 0.0)
        attrs = {
            "weight": strength,
            "edge_strength": strength,
            "signed_weight": signed_w,
            "delta_w": delta,
        }
        if G.has_edge(u, v):
            if strength > G[u][v].get("weight", 0.0):
                G[u][v].update(attrs)
        else:
            G.add_edge(u, v, **attrs)
    return G


def add_all_observed_nodes(G: nx.Graph, df: pl.DataFrame) -> None:
    nodes = set(df["gene_i_name"].to_list()) | set(df["gene_j_name"].to_list())
    G.add_nodes_from(str(x) for x in nodes)


# =============================================================================
# Community detection and module normalization
# =============================================================================


def detect_modules(G: nx.Graph, resolution: float, seed: int) -> Dict[str, int]:
    if G.number_of_nodes() == 0:
        return {}
    if G.number_of_edges() == 0:
        return {n: 0 for n in G.nodes()}

    try:
        import igraph as ig  # type: ignore
        import leidenalg  # type: ignore

        nodes = list(G.nodes())
        node_to_idx = {n: i for i, n in enumerate(nodes)}
        edges = [(node_to_idx[u], node_to_idx[v]) for u, v in G.edges()]
        weights = [float(G[u][v].get("weight", 1.0)) for u, v in G.edges()]
        ig_graph = ig.Graph(n=len(nodes), edges=edges, directed=False)
        ig_graph.es["weight"] = weights
        part = leidenalg.find_partition(
            ig_graph,
            leidenalg.RBConfigurationVertexPartition,
            weights="weight",
            resolution_parameter=float(resolution),
            seed=int(seed),
        )
        return {nodes[i]: int(cid) for cid, community in enumerate(part) for i in community}
    except Exception:
        pass

    try:
        import community as community_louvain  # type: ignore
        return community_louvain.best_partition(
            G,
            weight="weight",
            resolution=float(resolution),
            random_state=int(seed),
        )
    except Exception:
        pass

    communities = nx.algorithms.community.greedy_modularity_communities(G, weight="weight")
    part = {}
    for cid, comm in enumerate(communities):
        for node in comm:
            part[node] = cid
    return part


def normalize_module_ids(raw_part: Dict[str, int], all_nodes: Iterable[str], min_module_size: int) -> Tuple[Dict[str, str], Dict[str, List[str]]]:
    tmp: Dict[int, List[str]] = defaultdict(list)
    for node in all_nodes:
        node_s = str(node)
        if node_s in raw_part:
            tmp[int(raw_part[node_s])].append(node_s)
        else:
            tmp[-1].append(node_s)

    retained: List[Tuple[int, List[str]]] = []
    small_nodes: List[str] = []
    for cid, nodes in tmp.items():
        nodes = sorted(set(str(n) for n in nodes))
        if cid != -1 and len(nodes) >= int(min_module_size):
            retained.append((cid, nodes))
        else:
            small_nodes.extend(nodes)

    if not retained:
        all_sorted = sorted(set(str(n) for n in all_nodes))
        modules = {"M01": all_sorted}
        module_of = {n: "M01" for n in all_sorted}
        return module_of, modules

    retained.sort(key=lambda x: len(x[1]), reverse=True)
    largest_cid, largest_nodes = retained[0]
    merged_largest = sorted(set(largest_nodes) | set(small_nodes))
    retained[0] = (largest_cid, merged_largest)

    retained.sort(key=lambda x: len(x[1]), reverse=True)
    module_of: Dict[str, str] = {}
    modules: Dict[str, List[str]] = {}
    for rank, (_cid, nodes) in enumerate(retained, start=1):
        mid = f"M{rank:02d}"
        modules[mid] = sorted(set(nodes))
        for n in modules[mid]:
            module_of[n] = mid

    return module_of, modules


# =============================================================================
# Hub identification and module summaries
# =============================================================================


def choose_hub_count(n_nodes: int, hub_top_frac: float, min_hubs: int, max_hubs: int) -> int:
    if n_nodes <= 0:
        return 0
    n = int(math.ceil(n_nodes * float(hub_top_frac)))
    n = max(int(min_hubs), n)
    n = min(int(max_hubs), n)
    return min(n_nodes, n)


def compute_hubs(G_full: nx.Graph, modules: Dict[str, List[str]], hub_top_frac: float, min_hubs: int, max_hubs: int) -> Tuple[Dict[str, List[str]], pl.DataFrame]:
    hub_sets: Dict[str, List[str]] = {}
    rows = []

    global_wdeg = dict(G_full.degree(weight="weight"))
    global_deg = dict(G_full.degree())

    for mid, genes in sorted(modules.items()):
        sub = G_full.subgraph(genes).copy()
        intra_wdeg = dict(sub.degree(weight="weight"))
        intra_deg = dict(sub.degree())

        ranked = sorted(
            genes,
            key=lambda g: (float(intra_wdeg.get(g, 0.0)), int(intra_deg.get(g, 0))),
            reverse=True,
        )
        n_hub = choose_hub_count(len(genes), hub_top_frac, min_hubs, max_hubs)
        hubs = ranked[:n_hub]
        hub_sets[mid] = hubs

        for rank, gene in enumerate(hubs, start=1):
            incident_delta = [safe_float(G_full[gene][nb].get("delta_w"), 0.0) for nb in G_full.neighbors(gene)] if gene in G_full else []
            rows.append({
                "module_id": mid,
                "hub_rank": rank,
                "gene_name": gene,
                "within_abs_weighted_degree": round(float(intra_wdeg.get(gene, 0.0)), 8),
                "within_degree": int(intra_deg.get(gene, 0)),
                "global_abs_weighted_degree": round(float(global_wdeg.get(gene, 0.0)), 8),
                "global_degree": int(global_deg.get(gene, 0)),
                "mean_incident_delta_w": round(float(np.mean(incident_delta)), 8) if incident_delta else 0.0,
            })

    return hub_sets, pl.DataFrame(rows) if rows else pl.DataFrame()


def summarize_modules(G_full: nx.Graph, modules: Dict[str, List[str]], hub_sets: Dict[str, List[str]], node_type: Dict[str, str]) -> pl.DataFrame:
    rows = []
    for mid, genes in sorted(modules.items()):
        sub = G_full.subgraph(genes).copy()
        strengths = [float(d.get("weight", 0.0)) for _, _, d in sub.edges(data=True)]
        signed = [safe_float(d.get("signed_weight"), 0.0) for _, _, d in sub.edges(data=True)]
        deltas = [safe_float(d.get("delta_w"), 0.0) for _, _, d in sub.edges(data=True)]
        n_old = sum(1 for g in genes if node_type.get(g, "unknown") == "old")
        n_new = sum(1 for g in genes if node_type.get(g, "unknown") == "new")
        n_unknown = len(genes) - n_old - n_new
        rows.append({
            "module_id": mid,
            "n_genes": len(genes),
            "n_hubs": len(hub_sets.get(mid, [])),
            "top_hubs": ";".join(hub_sets.get(mid, [])[:10]),
            "n_internal_edges": sub.number_of_edges(),
            "internal_density": round(float(nx.density(sub)), 8) if sub.number_of_nodes() > 1 else 0.0,
            "mean_abs_w_ft_internal": round(float(np.mean(strengths)), 8) if strengths else 0.0,
            "median_abs_w_ft_internal": round(float(np.median(strengths)), 8) if strengths else 0.0,
            "mean_signed_w_ft_internal": round(float(np.mean(signed)), 8) if signed else 0.0,
            "mean_delta_w_internal": round(float(np.mean(deltas)), 8) if deltas else 0.0,
            "positive_delta_frac_internal": round(float(np.mean(np.array(deltas) > 0)), 8) if deltas else 0.0,
            "n_old_nodes": n_old,
            "n_new_nodes": n_new,
            "n_unknown_nodes": n_unknown,
        })
    return pl.DataFrame(rows)


def make_module_assignment_table(modules: Dict[str, List[str]], node_type: Dict[str, str], G_full: nx.Graph) -> pl.DataFrame:
    rows = []
    global_wdeg = dict(G_full.degree(weight="weight"))
    global_deg = dict(G_full.degree())
    for mid, genes in sorted(modules.items()):
        for gene in genes:
            rows.append({
                "gene_name": gene,
                "module_id": mid,
                "node_type": node_type.get(gene, "unknown"),
                "global_abs_weighted_degree": round(float(global_wdeg.get(gene, 0.0)), 8),
                "global_degree": int(global_deg.get(gene, 0)),
            })
    return pl.DataFrame(rows)


# =============================================================================
# Gene-set export
# =============================================================================


def export_gene_sets(out_dir: str, modules: Dict[str, List[str]], hub_sets: Dict[str, List[str]]) -> None:
    gene_set_dir = ensure_dir(os.path.join(out_dir, "gene_sets"))
    module_gene_dir = ensure_dir(os.path.join(gene_set_dir, "module_genes"))
    module_hub_dir = ensure_dir(os.path.join(gene_set_dir, "module_hubs"))

    for mid, genes in sorted(modules.items()):
        write_gene_list(os.path.join(module_gene_dir, f"{mid}_genes.txt"), genes)
        write_gene_list(os.path.join(module_hub_dir, f"{mid}_hubs.txt"), hub_sets.get(mid, []))


# =============================================================================
# Analysis metadata writing
# =============================================================================


def write_analysis_metadata(
    path: str,
    *,
    edge_table: str,
    out_dir: str,
    args: argparse.Namespace,
    observed_nodes: int,
    full_edges: int,
    module_edges: int,
    modules_total: int,
    assigned_nodes_total: int,
    hub_genes_total: int,
) -> None:
    metadata = {
        "task": "Trait-aware bulk network downstream analysis",
        "edge_table": edge_table,
        "out_dir": out_dir,
        "random_seed": int(args.seed),
        "seed": int(args.seed),  # backward-compatible alias for older downstream readers
        "weight_col": str(args.weight_col),
        "analysis_weight": f"abs({args.weight_col})",
        "module_top_frac": float(args.module_top_frac),
        "min_abs_weight": None if args.min_abs_weight is None else float(args.min_abs_weight),
        "min_module_size": int(args.min_module_size),
        "resolution": float(args.resolution),
        "hub_top_frac": float(args.hub_top_frac),
        "min_hubs": int(args.min_hubs),
        "max_hubs": int(args.max_hubs),
        "observed_nodes": int(observed_nodes),
        "full_edges": int(full_edges),
        "module_edges": int(module_edges),
        "modules_total": int(modules_total),
        "assigned_nodes_total": int(assigned_nodes_total),
        "hub_genes_total": int(hub_genes_total),
        "small_modules_policy": f"raw modules < {int(args.min_module_size)} merged into M01",
        "plotting_inputs": {
            "analysis_edge_table": "tables/analysis_edge_table.parquet",
            "module_assignment": "tables/module_assignment.csv",
            "hub_gene_summary": "tables/hub_gene_summary.csv",
        },
    }
    with open(path, "w") as f:
        yaml.safe_dump(metadata, f, allow_unicode=True, sort_keys=False)


# =============================================================================
# Main Run04 workflow
# =============================================================================


def main() -> None:
    args = parse_args()
    random.seed(args.seed)
    np.random.seed(args.seed)

    edge_table = resolve_edge_table(args)
    out_dir = ensure_dir(os.path.abspath(os.path.expanduser(args.out_dir)))
    tables_dir = ensure_dir(os.path.join(out_dir, "tables"))

    print("=" * 80)
    print("Trait-aware bulk network downstream analysis")
    print("=" * 80)
    print(f"edge_table        : {edge_table}")
    print(f"out_dir           : {out_dir}")
    print(f"signed_weight_col : {args.weight_col}")
    print(f"analysis_weight   : abs({args.weight_col})")
    print(f"module_top_frac   : {args.module_top_frac}")
    print(f"min_abs_weight    : {args.min_abs_weight}")
    print(f"min_module_size   : {args.min_module_size}")
    print(f"resolution        : {args.resolution}")
    print(f"random_seed       : {args.seed}  # reproducibility seed, not a data split ID")

    df = load_edge_table(edge_table, args.weight_col)
    node_type = get_node_type_map(df)

    G_full = build_graph_from_edges(df, signed_weight_col=args.weight_col)
    add_all_observed_nodes(G_full, df)

    module_edges = select_module_edges(df, args.module_top_frac, args.min_abs_weight)
    G_module = build_graph_from_edges(module_edges, signed_weight_col=args.weight_col)
    add_all_observed_nodes(G_module, df)

    print(f"observed_nodes    : {G_full.number_of_nodes():,}")
    print(f"full_edges        : {G_full.number_of_edges():,}")
    print(f"module_edges      : {G_module.number_of_edges():,}")

    raw_part = detect_modules(G_module, resolution=args.resolution, seed=args.seed)
    all_nodes = list(G_full.nodes())
    module_of, modules = normalize_module_ids(raw_part, all_nodes, args.min_module_size)

    hub_sets, hub_df = compute_hubs(
        G_full=G_full,
        modules=modules,
        hub_top_frac=args.hub_top_frac,
        min_hubs=args.min_hubs,
        max_hubs=args.max_hubs,
    )

    module_summary = summarize_modules(G_full, modules, hub_sets, node_type)
    assignment = make_module_assignment_table(modules, node_type, G_full)

    total_module_nodes = sum(len(v) for v in modules.values())
    total_modules = len(modules)
    n_hubs = sum(len(v) for v in hub_sets.values())

    module_count_summary = pl.DataFrame([
        {"metric": "observed_nodes", "value": str(G_full.number_of_nodes())},
        {"metric": "assigned_nodes_total", "value": str(total_module_nodes)},
        {"metric": "modules_total", "value": str(total_modules)},
        {"metric": "small_raw_modules_merged_into", "value": "M01"},
        {"metric": "min_module_size", "value": str(int(args.min_module_size))},
    ])

    # Tables used by downstream biological interpretation.
    assignment.write_csv(os.path.join(tables_dir, "module_assignment.csv"))
    module_summary.write_csv(os.path.join(tables_dir, "module_summary.csv"))
    module_count_summary.write_csv(os.path.join(tables_dir, "module_count_summary.csv"))
    if hub_df.height > 0:
        hub_df.write_csv(os.path.join(tables_dir, "hub_gene_summary.csv"))
    else:
        pl.DataFrame(schema={
            "module_id": pl.Utf8,
            "hub_rank": pl.Int64,
            "gene_name": pl.Utf8,
            "within_abs_weighted_degree": pl.Float64,
            "within_degree": pl.Int64,
            "global_abs_weighted_degree": pl.Float64,
            "global_degree": pl.Int64,
            "mean_incident_delta_w": pl.Float64,
        }).write_csv(os.path.join(tables_dir, "hub_gene_summary.csv"))
    module_edges.write_parquet(os.path.join(tables_dir, "module_edges.parquet"))

    # Plotting interface table. This is the filtered full edge table after adding edge_strength.
    # The separate plotting script reads this file and does not redo community detection.
    df.write_parquet(os.path.join(tables_dir, "analysis_edge_table.parquet"))

    export_gene_sets(out_dir, modules, hub_sets)

    write_analysis_metadata(
        os.path.join(tables_dir, "analysis_metadata.yaml"),
        edge_table=edge_table,
        out_dir=out_dir,
        args=args,
        observed_nodes=G_full.number_of_nodes(),
        full_edges=G_full.number_of_edges(),
        module_edges=G_module.number_of_edges(),
        modules_total=total_modules,
        assigned_nodes_total=total_module_nodes,
        hub_genes_total=n_hubs,
    )

    print("-" * 80)
    print(f"modules_detected      : {total_modules}")
    print(f"assigned_nodes_total  : {total_module_nodes:,} / {G_full.number_of_nodes():,}")
    print(f"small_modules_policy  : raw modules < {args.min_module_size} merged into M01")
    print(f"hub_genes_total       : {n_hubs}")
    print("outputs:")
    print("  tables/analysis_edge_table.parquet")
    print("  tables/analysis_metadata.yaml")
    print("  tables/module_assignment.csv")
    print("  tables/module_summary.csv")
    print("  tables/module_count_summary.csv")
    print("  tables/hub_gene_summary.csv")
    print("  tables/module_edges.parquet")
    print("  gene_sets/module_genes/Mxx_genes.txt")
    print("  gene_sets/module_hubs/Mxx_hubs.txt")
    print("=" * 80)


if __name__ == "__main__":
    main()
