#!/usr/bin/env python3
r"""
==============================================================================
Run02: Tissue-Specific DeepTAN Fine-Tuning
==============================================================================

Purpose
-------
Fine-tune an scRNA-pretrained DeepTAN model on a user-defined tissue scRNA
LitData directory generated by Run01.

Pipeline position
-----------------
Run01: user-defined tissue scRNA files -> LitData
Run02: LitData -> tissue-specific fine-tuned DeepTAN checkpoint
Run03: LitData + fine-tuned checkpoint -> tissue-specific latent gene network

Core computation
----------------
This script keeps the original fine-tuning logic:

  1. Load the scRNA-pretrained DeepTAN checkpoint.
  2. Load tissue-specific LitData generated by Run01.
  3. Adapt the classification head when the tissue-specific label dimension
     differs from the pretrained label dimension.
  4. Fine-tune the model using reconstruction, classification, and anchor losses.
  5. Save checkpoints, TensorBoard logs, and finetune metadata.

User-facing workflow
--------------------
The recommended GitHub workflow is single-run:

    python src/Run02_Tissue_finetune.py \
        --config configs/Run02_Tissue_finetune.yaml

Optional overrides:

    python src/Run02_Tissue_finetune.py \
        --config configs/Run02_Tissue_finetune.yaml \
        --tissue ExampleTissue

Legacy multi-split behavior is still supported. If the configured LitData path
contains subdirectories such as 42/, 43/, 44/, each valid subdirectory can be
treated as one split. In the standard single-run workflow, the LitData directory
itself directly contains trn/, val/, tst/, and litdata_others2save.pkl.

Notes
-----
The configuration field `seed` is a training reproducibility seed. It is not a
data split identifier in the standard single-run workflow.

Author: DeepTAN Tissue-Specific Fine-Tuning Pipeline
"""

import argparse
import copy
import os
import pickle
import sys
from typing import Any, Dict, List, Optional, Tuple

import lightning as ltn
import numpy as np
import polars as pl
import torch
import torch.nn as nn
import torch.nn.functional as F
import yaml
from itertools import accumulate
from lightning import LightningDataModule, Trainer
from lightning.pytorch.callbacks import (
    EarlyStopping,
    LearningRateMonitor,
    ModelCheckpoint,
)
from lightning.pytorch.loggers import TensorBoardLogger
from loguru import logger
from torch.optim.adamw import AdamW
from torch_geometric.data import Data as GData
from torchmetrics import MetricCollection
from torchmetrics.classification import (
    MulticlassAccuracy,
    MulticlassAUROC,
    MulticlassF1Score,
    MulticlassPrecision,
    MulticlassRecall,
)
from torchmetrics.regression import (
    MeanAbsoluteError,
    MeanSquaredError,
    PearsonCorrCoef,
)


# ── Optional local DeepTAN source checkout ───────────────────────────────────
# Set DEEPTAN_SRC in the shell wrapper when DeepTAN is not installed as a package.
# Example:
#   export DEEPTAN_SRC="/path/to/deeptan-dev/src"
_LOCAL_DEEPTAN = os.environ.get("DEEPTAN_SRC", "").strip()
if _LOCAL_DEEPTAN and _LOCAL_DEEPTAN not in sys.path:
    sys.path.insert(0, _LOCAL_DEEPTAN)
# ────────────────────────────────────────────────────────────────────────────


# ── DeepTAN imports ─────────────────────────────────────────────────────────
import deeptan.constants as const
from deeptan.graph.modules import AMSGP, FocalLoss, GE_Decoder, GLabelPredictor
from deeptan.graph.model import DeepTAN
from deeptan.utils.data import (
    DeepTANDataModule,
    DeepTANDataModuleLit,
    NMICGraphDataset,
    NMICGraphDatasetRely,
    celltypes_class_weights,
)
from deeptan.utils.uni import get_map_location, random_string, time_string

# ============================================================================
# 1. Configuration & Defaults
# ============================================================================

DEFAULT_CONFIG = {
    # ── Paths ───────────────────────────────────────────────────────────────
    "pretrained_ckpt": "checkpoints/best_model.ckpt",
    "nmic_npz": "data/NMIC.npz",
    "output_dir": "output/finetune",

    # ── Tissue datasets ─────────────────────────────────────────────────────
    "tissues": {
        "Seedling": {
            "litdata": "data/Seedling/litdata",
        },
    },

    # ── Training order ──────────────────────────────────────────────────────
    "tissue_order": ["Seedling"],

    # ── Hyperparameters ─────────────────────────────────────────────────────
    "base_lr": 3e-5,
    "lr_multipliers": {
        "embed": 0.0,
        "feature_proj": 0.1,
        "fusion_mlp": 0.1,
        "gat_layers": 0.2,
        "pooling": 0.2,
        "ge_decoder": 0.3,
        "g_label_predictor": 1.0,
    },
    "weight_decay": 1e-5,
    "warmup_epochs": 3,
    "max_epochs": 50,
    "min_epochs": 10,
    "es_patience": 9,
    "batch_size": 32,
    "accumulate_grad_batches": 1,
    "gradient_clip_val": 1.0,

    # ── Loss configuration ──────────────────────────────────────────────────
    "lambda_anchor": 0.02,
    "focal_gamma": 1.5,
    "loss_zero_coeff": 0.5,

    # ── LR Scheduler ────────────────────────────────────────────────────────
    "scheduler": "cosine_warm_restarts",
    "cosine_T0": 9,
    "cosine_T_mult": 1,
    "plateau_patience": 5,
    "plateau_factor": 0.5,
    "min_lr": 1e-7,

    # ── Device ──────────────────────────────────────────────────────────────
    "accelerator": "auto",
    "devices": "auto",
    "precision": "32-true",
    "n_workers": 4,

    # ── Misc ────────────────────────────────────────────────────────────────
    "seed": 42,
}


def load_config(config_path: Optional[str] = None) -> Dict[str, Any]:
    """Load configuration from YAML file, falling back to defaults."""
    config = copy.deepcopy(DEFAULT_CONFIG)
    if config_path and os.path.exists(config_path):
        with open(config_path, "r") as f:
            user_config = yaml.safe_load(f)
        if user_config:
            for k, v in user_config.items():
                if isinstance(v, dict) and isinstance(config.get(k), dict):
                    config[k].update(v)
                else:
                    config[k] = v
        logger.info(f"Loaded configuration from {config_path}")
    else:
        logger.warning("No config file provided or found; using defaults.")
    return config


# ============================================================================
# 1b. [SPLIT-1] Multi-Split Discovery
# ============================================================================

def _discover_splits(litdata_base: str) -> List[str]:
    """
    [SPLIT-1] Automatically scan child directories under a LitData parent directory as different data splits.

    Detection logic:
      - If litdata_base itself contains litdata_others2save.pkl, use legacy single-directory mode and return an empty list.
      - Otherwise, scan child directories under litdata_base and keep valid split directories containing the metadata pkl.

    Example layout for multi-split mode:
        rosette/litdata/
        ├── 42/  (trn/ val/ tst/ litdata_others2save.pkl)
        ├── 43/
        └── 44/

    Example layout for legacy/single-split mode:
        rosette/litdata/
        ├── trn/
        ├── val/
        ├── tst/
        └── litdata_others2save.pkl

    Returns:
        A naturally sorted list of split IDs. An empty list indicates legacy mode where litdata_base itself is the valid directory.
    """
    pkl_name = const.fname.litdata_others2save_pkl

    # Backward compatibility: litdata_base itself is a valid LitData directory
    if os.path.exists(os.path.join(litdata_base, pkl_name)):
        return []

    # Scan child directories
    if not os.path.isdir(litdata_base):
        return []

    splits = []
    for entry in os.listdir(litdata_base):
        subdir = os.path.join(litdata_base, entry)
        if os.path.isdir(subdir) and os.path.exists(os.path.join(subdir, pkl_name)):
            splits.append(entry)

    # Natural sorting: numeric names are sorted numerically; non-numeric names lexicographically
    def _sort_key(s):
        try:
            return (0, int(s), s)
        except ValueError:
            return (1, 0, s)

    splits.sort(key=_sort_key)

    return splits


# ============================================================================
# 2. CV Weights Loading
# ============================================================================

def load_cv_weights(cv_weights_path: str, dict_node_names: Dict[str, int]) -> torch.Tensor:
    """
    Load gene CV weights and align with dict_node_names ordering.
    CSV columns: gene, cv_weight (range [0.5, 1.0]).
    """
    num_genes = len(dict_node_names)
    weights = torch.ones(num_genes, dtype=torch.float32) * 0.75

    if not os.path.exists(cv_weights_path):
        logger.warning(f"CV weights not found: {cv_weights_path}. Using uniform 0.75.")
        return weights

    df = pl.read_csv(cv_weights_path)
    if "gene" not in df.columns or "cv_weight" not in df.columns:
        logger.warning("CV weights CSV must have 'gene' and 'cv_weight' columns.")
        return weights

    cv_dict = dict(zip(df["gene"].to_list(), df["cv_weight"].to_list()))
    matched = 0
    for gene_name, idx in dict_node_names.items():
        if gene_name in cv_dict:
            weights[idx] = cv_dict[gene_name]
            matched += 1

    logger.info(f"CV weights: matched {matched}/{num_genes} genes, "
                f"min={weights.min():.4f}, max={weights.max():.4f}, mean={weights.mean():.4f}")
    return weights


# ============================================================================
# 3. Fine-Tunable DeepTAN Module (Optimized)
# ============================================================================

class DeepTANFineTune(ltn.LightningModule):
    """
    Fine-tuning wrapper for DeepTAN (Plan A1, optimized v6 + multi-split).

    This module keeps the original tissue fine-tuning behavior: reuse the
    pretrained DeepTAN backbone, adapt the classification head when needed,
    freeze the embedding layer, and optimize reconstruction, classification,
    and anchor losses.
    """

    def __init__(
        self,
        pretrained_model: DeepTAN,
        cv_weights: torch.Tensor,
        class_weights: Optional[List[float]],
        config: Dict[str, Any],
        tissue_num_classes: Optional[int] = None,
    ):
        super().__init__()
        self.save_hyperparameters(ignore=["pretrained_model", "cv_weights"])

        # ── Core model (from pretrained) ────────────────────────────────────
        self.amsgp = pretrained_model.amsgp
        self.ge_decoder = pretrained_model.ge_decoder
        self.g_label_predictor = pretrained_model.g_label_predictor

        # ── Copy essential attributes ───────────────────────────────────────
        self.dict_node_names = pretrained_model.dict_node_names
        self.all_node_names = pretrained_model.all_node_names
        self.num_all_nodes = pretrained_model.num_all_nodes
        self.input_dim = pretrained_model.input_dim
        self.is_regression = pretrained_model.is_regression

        # ── [FIX-7] Tissue-specific class-count adaptation ─────────────────
        self.pretrained_num_classes = pretrained_model.output_g_label_dim
        if tissue_num_classes is not None and tissue_num_classes != self.pretrained_num_classes:
            self.num_classes = tissue_num_classes
            self.output_g_label_dim = tissue_num_classes
            logger.warning(
                f"  [FIX-7] class-count mismatch: pretrained={self.pretrained_num_classes}, "
                f"current_tissue={tissue_num_classes}. Rebuilding the GLabelPredictor output layer."
            )
            self._adapt_g_label_predictor(
                pretrained_model, tissue_num_classes,
            )
        else:
            self.num_classes = self.pretrained_num_classes
            self.output_g_label_dim = self.pretrained_num_classes
            self._rebuilt_predictor_param_names = set()
            logger.info(
                f"  class count is consistent: {self.num_classes}; no GLabelPredictor rebuild is needed"
            )

        # ── Configuration ───────────────────────────────────────────────────
        self.config = config
        self.base_lr = config["base_lr"]
        self.lr_multipliers = config["lr_multipliers"]
        self.lambda_anchor = config["lambda_anchor"]
        self.warmup_epochs = config["warmup_epochs"]
        self.loss_zero_coeff = config["loss_zero_coeff"]

        # ── CV weights ──────────────────────────────────────────────────────
        self.register_buffer("cv_weights", cv_weights)

        # ── [FIX-3] Class weights → focal_alpha ────────────────────────────
        if class_weights is not None:
            if len(class_weights) != self.num_classes:
                logger.error(
                    f"  class_weights dimension ({len(class_weights)}) does not match num_classes "
                    f"({self.num_classes}); using uniform weights.\n"
                    f"  Please check whether the number of columns in celltype_onehot.parquet matches this tissue label set."
                )
                focal_alpha = torch.ones(self.num_classes, dtype=torch.float32)
            else:
                focal_alpha = torch.tensor(class_weights, dtype=torch.float32)
                focal_alpha = (focal_alpha + focal_alpha.mean()) / 2.0
        else:
            focal_alpha = torch.ones(self.num_classes, dtype=torch.float32)
        self.register_buffer("focal_alpha", focal_alpha)
        self.focal_gamma = config["focal_gamma"]

        # ── [FIX-6] Pre-instantiated FocalLoss ─────────────────────────────
        self.focal_loss_fn = FocalLoss(
            gamma=self.focal_gamma,
            alpha=self.focal_alpha,
            reduction="mean",
        )

        # ── [FIX-4] L2 anchor buffers ──────────────────────────────────────
        self._anchor_param_names = []
        for name, param in self.named_parameters():
            if name in self._rebuilt_predictor_param_names:
                logger.debug(f"  Skip anchor regularization for rebuilt parameter: {name}")
                continue
            buffer_name = "_anchor_" + name.replace(".", "__")
            self.register_buffer(buffer_name, param.detach().clone(), persistent=True)
            self._anchor_param_names.append((name, buffer_name))

        # ── Freeze embed layer ──────────────────────────────────────────────
        self._freeze_embed_layer()

        # ── [FIX-4] loss_smooth buffer ──────────────────────────────────────
        init_loss_smooth = 0.1
        if hasattr(pretrained_model, "loss_smooth") and pretrained_model.loss_smooth != 0.0:
            init_loss_smooth = pretrained_model.loss_smooth
        self.register_buffer("_loss_smooth", torch.tensor(init_loss_smooth, dtype=torch.float32))

        self._prev_epoch = -1
        self._init_metrics()
        self.float()

    # ── Properties ──────────────────────────────────────────────────────────

    @property
    def loss_smooth(self) -> float:
        return self._loss_smooth.item()

    @loss_smooth.setter
    def loss_smooth(self, value: float):
        self._loss_smooth.fill_(value)

    # ── Freezing ────────────────────────────────────────────────────────────

    def _freeze_embed_layer(self):
        embed_layer = self.amsgp.node_embedding_layers.embed
        for param in embed_layer.parameters():
            param.requires_grad = False
        n_frozen = sum(p.numel() for p in embed_layer.parameters())
        logger.info(f"Frozen embed layer: {n_frozen:,} parameters")

    def verify_embed_frozen(self) -> bool:
        for name, param in self.amsgp.node_embedding_layers.embed.named_parameters():
            if param.requires_grad:
                logger.error(f"ALERT: embed param '{name}' has requires_grad=True!")
                return False
        return True

    # ── [FIX-7] GLabelPredictor adaptation ──────────────────────────────────

    def _adapt_g_label_predictor(
        self,
        pretrained_model: "DeepTAN",
        tissue_num_classes: int,
    ):
        """
        [FIX-7] Rebuild GLabelPredictor output layer for tissue-specific class count.
        Preserves hidden layers and replaces only the final Linear layer.
        The new tissue-specific output layer is Xavier-initialized for normal
        fine-tuning.
        """
        predictor = self.g_label_predictor
        self._rebuilt_predictor_param_names = set()

        # ── Strategy 1: Known attribute names ────────────────────────────────
        candidate_attr_names = ["output_layer", "fc", "classifier", "head", "out_proj"]
        target_linear = None
        target_attr_name = None

        for attr_name in candidate_attr_names:
            if hasattr(predictor, attr_name):
                candidate = getattr(predictor, attr_name)
                if isinstance(candidate, nn.Linear):
                    target_linear = candidate
                    target_attr_name = attr_name
                    logger.info(
                        f"  [FIX-7] strategy 1 matched: predictor.{attr_name} = "
                        f"Linear({candidate.in_features}, {candidate.out_features})"
                    )
                    break

        # ── Strategy 2: Match by out_features in direct children ─────────────
        if target_linear is None:
            for child_name, child_module in predictor.named_children():
                if isinstance(child_module, nn.Linear):
                    if child_module.out_features == self.pretrained_num_classes:
                        target_linear = child_module
                        target_attr_name = child_name
                        logger.info(
                            f"  [FIX-7] strategy 2 matched: predictor.{child_name}"
                        )
                        break

        # ── Strategy 3: Deep search ──────────────────────────────────────────
        if target_linear is None:
            for name, module in predictor.named_modules():
                if name == "":
                    continue
                if isinstance(module, nn.Linear) and module.out_features == self.pretrained_num_classes:
                    target_linear = module
                    target_attr_name = name
            if target_linear is not None:
                logger.info(f"  [FIX-7] strategy 3 matched: predictor.{target_attr_name}")

        # ── Strategy 4: Fallback — last Linear ───────────────────────────────
        if target_linear is None:
            for name, module in predictor.named_modules():
                if name == "" or not isinstance(module, nn.Linear):
                    continue
                target_linear = module
                target_attr_name = name
            if target_linear is not None:
                logger.warning(
                    f"  [FIX-7] strategy 4 fallback: predictor.{target_attr_name}"
                )

        if target_linear is None:
            logger.error("  [FIX-7] no Linear layer found; skipping predictor adaptation.")
            self._rebuilt_predictor_param_names = set()
            return

        old_out_features = target_linear.out_features
        in_features = target_linear.in_features
        has_bias = target_linear.bias is not None

        if old_out_features != self.pretrained_num_classes:
            logger.warning(
                f"  [FIX-7] out_features={old_out_features} "
                f"≠ pretrained_num_classes={self.pretrained_num_classes}"
            )

        logger.info(
            f"  [FIX-7] replacing Linear({in_features}, {old_out_features}) "
            f"→ Linear({in_features}, {tissue_num_classes})"
        )

        # ── Create and initialize the new Linear layer ─────────────────────
        new_linear = nn.Linear(in_features, tissue_num_classes, bias=has_bias)
        nn.init.xavier_uniform_(new_linear.weight)
        if has_bias:
            nn.init.zeros_(new_linear.bias)
        init_method = "Xavier"

        # ── Replace the old layer ─────────────────────────────────────────
        parts = target_attr_name.split(".")
        if len(parts) == 1:
            setattr(predictor, parts[0], new_linear)
        else:
            parent = predictor
            for part in parts[:-1]:
                parent = parent[int(part)] if part.isdigit() else getattr(parent, part)
            last_part = parts[-1]
            if last_part.isdigit():
                parent[int(last_part)] = new_linear
            else:
                setattr(parent, last_part, new_linear)

        # ── Verify replacement ────────────────────────────────────────────
        replaced = predictor
        for part in parts:
            replaced = replaced[int(part)] if part.isdigit() else getattr(replaced, part)
        assert isinstance(replaced, nn.Linear) and replaced.out_features == tissue_num_classes

        for pname, _ in new_linear.named_parameters():
            full_name = f"g_label_predictor.{target_attr_name}.{pname}"
            self._rebuilt_predictor_param_names.add(full_name)

        logger.info(f"  [FIX-7] ✓ output layer rebuilt ({init_method})")

    # ── Forward Pass ────────────────────────────────────────────────────────

    def forward(self, batch: GData) -> Dict[str, Any]:
        node_batch = getattr(
            batch, "batch",
            torch.zeros(batch.x.size(0), dtype=torch.long, device=self.device),
        )
        if batch.x.dtype != torch.float32:
            batch.x = batch.x.float()
        if batch.edge_index.dtype != torch.long:
            batch.edge_index = batch.edge_index.long()

        z, ids = self.amsgp(
            node_names=batch.node_names,
            x=batch.x,
            edge_index=batch.edge_index,
            batch=node_batch,
        )

        recon_node_emb, pred_feat_values = self.ge_decoder(
            z, self.amsgp.node_embedding_layers.embed.weight
        )

        pred_labels = self.g_label_predictor(z)

        pred_nonzero, pred_zeros, valid_node_ids = self._create_node_masks_aligned(
            batch.node_names, pred_feat_values, ids
        )

        return {
            "embedding": z,
            "node_recon": recon_node_emb,
            "label_pred": pred_labels,
            "pred_nonzero": pred_nonzero,
            "pred_zeros": pred_zeros,
            "valid_node_ids": valid_node_ids,
            "obs_name": batch.obs_name,
            "node_names": batch.node_names,
            "ids": ids,
        }

    # ── [FIX-1] Node ordering alignment ────────────────────────────────────

    def _create_node_masks_aligned(
        self,
        batch_node_names: List[List[str]],
        pred_feat_values: torch.Tensor,
        ids: torch.Tensor,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        device = pred_feat_values.device
        counts = [len(nodes) for nodes in batch_node_names]
        cum_counts = [0] + list(accumulate(counts))
        B = pred_feat_values.shape[0]
        N_all = pred_feat_values.shape[1]

        if pred_feat_values.dim() == 3 and pred_feat_values.shape[2] == 1:
            pred_2d = pred_feat_values.squeeze(2)
        elif pred_feat_values.dim() == 3:
            pred_2d = pred_feat_values.flatten(1)
        else:
            pred_2d = pred_feat_values

        pred_valid_list = []
        for i in range(B):
            start = cum_counts[i]
            end = cum_counts[i + 1]
            node_indices = ids[start:end]
            pred_valid_list.append(pred_2d[i, node_indices])

        pred_nonzero = torch.cat(pred_valid_list)
        valid_node_ids = ids.clone()

        mask = torch.zeros(B, N_all, dtype=torch.bool, device=device)
        for i in range(B):
            start = cum_counts[i]
            end = cum_counts[i + 1]
            node_indices = ids[start:end]
            mask[i, node_indices] = True
        pred_zeros = pred_2d[~mask]

        return pred_nonzero, pred_zeros, valid_node_ids

    # ── Training / Validation / Test / Predict Steps ────────────────────────

    def training_step(self, batch: GData, batch_idx: int):
        return self._shared_step(batch, "train")

    def validation_step(self, batch: GData, batch_idx: int):
        return self._shared_step(batch, "val")

    def test_step(self, batch: GData, batch_idx: int):
        return self._shared_step(batch, "test")

    def _shared_step(self, batch: GData, stage: str) -> torch.Tensor:
        outputs = self(batch)
        losses = self._compute_losses(outputs, batch, stage)

        if batch.y is not None and not self.is_regression:
            preds = outputs["label_pred"]
            _y = batch.y if isinstance(batch.y, torch.Tensor) else torch.tensor(batch.y, device=self.device)
            if _y.ndim > 1 and _y.shape[1] > 1:
                targets_class = torch.argmax(_y, dim=1)
            else:
                targets_class = _y.long()

            self.metrics_class[f"{stage}_metrics"].update(preds, targets_class)
            probs = F.softmax(preds, dim=1)
            self.metrics_auroc[f"{stage}_metrics"].update(probs, targets_class)

        for k, v in losses.items():
            self.log(f"{stage}/{k}", v, prog_bar=(k == "loss"),
                     on_step=True, on_epoch=True, sync_dist=True,
                     batch_size=batch.num_graphs if hasattr(batch, "num_graphs") else 1)

        return losses["loss"]

    # ── Epoch-end hooks ─────────────────────────────────────────────────────

    def on_train_epoch_end(self):
        self._log_epoch_metrics("train")

    def on_validation_epoch_end(self):
        self._log_epoch_metrics("val")

    def on_test_epoch_end(self):
        self._log_epoch_metrics("test")

    def _log_epoch_metrics(self, stage: str):
        if self.trainer.sanity_checking:
            return
        bs = 1
        if not self.is_regression and f"{stage}_metrics" in self.metrics_class:
            mc = self.metrics_class[f"{stage}_metrics"].compute()
            for name, val in mc.items():
                self.log(name, val, sync_dist=True, batch_size=bs)
            self.metrics_class[f"{stage}_metrics"].reset()

            ma = self.metrics_auroc[f"{stage}_metrics"].compute()
            for name, val in ma.items():
                self.log(name, val, sync_dist=True, batch_size=bs)
            self.metrics_auroc[f"{stage}_metrics"].reset()

    # ── Loss Computation ────────────────────────────────────────────────────

    def _compute_losses(self, outputs: Dict, batch: GData, stage: str) -> Dict:
        losses = {}

        target = batch.x.squeeze(-1).float()
        pred_nonzero = outputs["pred_nonzero"]
        pred_zeros = outputs["pred_zeros"]
        valid_ids = outputs["valid_node_ids"]

        per_node_cv = self.cv_weights[valid_ids]
        mse_per_node = (pred_nonzero - target) ** 2
        cv_weighted_mse = (mse_per_node * per_node_cv).mean()
        losses["recon_MSE"] = cv_weighted_mse

        if pred_zeros.numel() > 0:
            recon_loss_zeros = F.mse_loss(pred_zeros, torch.zeros_like(pred_zeros))
        else:
            recon_loss_zeros = torch.tensor(0.0, device=self.device)
        losses["recon_zeros"] = recon_loss_zeros
        losses["recon"] = cv_weighted_mse + self.loss_zero_coeff * recon_loss_zeros

        if batch.y is None:
            losses["label"] = torch.tensor(0.0, device=self.device)
        else:
            _y = batch.y if isinstance(batch.y, torch.Tensor) else torch.tensor(batch.y, device=self.device)
            if self.is_regression:
                losses["label"] = F.mse_loss(outputs["label_pred"], _y)
            else:
                if _y.ndim > 1 and _y.shape[1] > 1:
                    _y = torch.argmax(_y, dim=1)
                losses["label"] = self.focal_loss_fn(outputs["label_pred"], _y)

        losses["anchor"] = self._compute_anchor_loss()

        total_loss, unweighted_loss = self._balance_losses(losses, stage)
        losses["loss"] = total_loss
        losses["loss_unweighted"] = unweighted_loss

        return losses

    def _compute_anchor_loss(self) -> torch.Tensor:
        if self.current_epoch < self.warmup_epochs:
            return torch.tensor(0.0, device=self.device)

        l2_sum = torch.tensor(0.0, device=self.device)
        param_count = 0

        for name, buffer_name in self._anchor_param_names:
            parts = name.split(".")
            param = self
            try:
                for part in parts:
                    param = getattr(param, part)
            except AttributeError:
                continue

            if not isinstance(param, torch.Tensor) or not param.requires_grad:
                continue

            pretrained_val = getattr(self, buffer_name)
            l2_sum = l2_sum + torch.sum((param - pretrained_val) ** 2)
            param_count += param.numel()

        if param_count > 0:
            l2_sum = l2_sum / param_count

        return self.lambda_anchor * l2_sum

    def _balance_losses(self, losses: Dict, stage: str) -> Tuple[torch.Tensor, torch.Tensor]:
        cycle_phase = self.current_epoch % 3
        anchor_loss = losses["anchor"]

        if stage == "train":
            if cycle_phase == 0:
                alpha, beta = 1.0, 0.0
            elif cycle_phase == 1:
                alpha, beta = 0.0, 1.0
            else:
                alpha, beta = 0.7, 0.3

            if beta > 0 and self.loss_smooth > 1e-8:
                scaled_label = losses["label"] * (self.loss_smooth / losses["label"].detach().clamp(min=1e-8))
            else:
                scaled_label = losses["label"]

            total_loss = alpha * losses["recon"] + beta * scaled_label + anchor_loss
            self.loss_smooth = 0.1 * total_loss.detach().item() + 0.9 * self.loss_smooth
        else:
            if self.loss_smooth > 1e-8:
                scaled_label = losses["label"] * (self.loss_smooth / losses["label"].detach().clamp(min=1e-8))
            else:
                scaled_label = losses["label"]
            total_loss = 0.5 * losses["recon"] + 0.5 * scaled_label + anchor_loss

        unweighted_loss = 0.5 * losses["recon"] + 0.5 * losses["label"]
        return total_loss, unweighted_loss

    # ── Epoch Callbacks ─────────────────────────────────────────────────────

    def on_train_epoch_start(self) -> None:
        phase_names = {0: "RECON_FOCUS", 1: "LABEL_FOCUS", 2: "JOINT(0.7/0.3)"}
        phase = self.current_epoch % 3
        logger.info(
            f"Epoch {self.current_epoch} | Phase: {phase_names[phase]} | "
            f"λ_anchor: {self.lambda_anchor} | loss_smooth: {self.loss_smooth:.4f}"
        )

    # ── Optimizer ───────────────────────────────────────────────────────────

    def configure_optimizers(self):
        param_groups = self._build_param_groups()

        optimizer = AdamW(
            param_groups,
            weight_decay=self.config["weight_decay"],
            betas=(0.9, 0.999),
            eps=1e-8,
        )

        if self.config["scheduler"] == "cosine_warm_restarts":
            scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(
                optimizer,
                T_0=self.config["cosine_T0"],
                T_mult=self.config["cosine_T_mult"],
                eta_min=self.config["min_lr"],
            )
            return {
                "optimizer": optimizer,
                "lr_scheduler": {"scheduler": scheduler, "interval": "epoch", "frequency": 1},
            }
        else:
            scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                optimizer,
                mode="min",
                factor=self.config["plateau_factor"],
                patience=self.config["plateau_patience"],
                min_lr=self.config["min_lr"],
            )
            return {
                "optimizer": optimizer,
                "lr_scheduler": {
                    "scheduler": scheduler,
                    "monitor": "val/loss_unweighted",
                    "interval": "epoch",
                    "frequency": 1,
                    "strict": True,
                },
            }

    def _build_param_groups(self) -> List[Dict]:
        base_lr = self.base_lr
        mult = self.lr_multipliers

        embed_params = list(self.amsgp.node_embedding_layers.embed.parameters())
        feat_proj_params = list(self.amsgp.node_embedding_layers.feature_proj.parameters())
        fusion_mlp_params = list(self.amsgp.node_embedding_layers.fusion_mlp.parameters())
        gat_params = list(self.amsgp.node_embedding_layers._layers.parameters())
        norm_params = list(self.amsgp.node_embedding_layers.norm.parameters())

        pooling_params = (
            list(self.amsgp.sagpool1.parameters()) +
            list(self.amsgp.global_xgat_pool1.parameters()) +
            list(self.amsgp.global_sagpool1.parameters())
        )

        decoder_params = list(self.ge_decoder.parameters())
        predictor_params = list(self.g_label_predictor.parameters())

        groups = [
            {"params": embed_params, "lr": 0.0, "name": "embed"},
            {"params": feat_proj_params, "lr": base_lr * mult["feature_proj"], "name": "feature_proj"},
            {"params": fusion_mlp_params, "lr": base_lr * mult["fusion_mlp"], "name": "fusion_mlp"},
            {"params": gat_params + norm_params, "lr": base_lr * mult["gat_layers"], "name": "gat_layers"},
            {"params": pooling_params, "lr": base_lr * mult["pooling"], "name": "pooling"},
            {"params": decoder_params, "lr": base_lr * mult["ge_decoder"], "name": "ge_decoder"},
            {"params": predictor_params, "lr": base_lr * mult["g_label_predictor"], "name": "g_label_predictor"},
        ]

        for g in groups:
            n_total = sum(p.numel() for p in g["params"])
            n_train = sum(p.numel() for p in g["params"] if p.requires_grad)
            logger.info(f"  Param group '{g['name']}': lr={g['lr']:.2e}, "
                        f"total={n_total:,}, trainable={n_train:,}")
        return groups

    def _init_metrics(self):
        if not self.is_regression and self.num_classes is not None:
            metrics_class = MetricCollection({
                "F1_weighted": MulticlassF1Score(num_classes=self.num_classes, average="weighted"),
                "F1_macro": MulticlassF1Score(num_classes=self.num_classes, average="macro"),
                "F1_micro": MulticlassF1Score(num_classes=self.num_classes, average="micro"),
                "Accuracy": MulticlassAccuracy(num_classes=self.num_classes, average="weighted"),
                "Precision": MulticlassPrecision(num_classes=self.num_classes, average="weighted"),
                "Recall": MulticlassRecall(num_classes=self.num_classes, average="weighted"),
            })
            metrics_auroc = MetricCollection({
                "AUROC": MulticlassAUROC(
                    num_classes=self.num_classes, average="weighted", thresholds=None
                ),
            })
            self.metrics_class = nn.ModuleDict(
                {f"{k}_metrics": metrics_class.clone(prefix=f"{k}/label_")
                 for k in ["train", "val", "test"]}
            )
            self.metrics_auroc = nn.ModuleDict(
                {f"{k}_metrics": metrics_auroc.clone(prefix=f"{k}/label_")
                 for k in ["train", "val", "test"]}
            )
        else:
            self.metrics_class = nn.ModuleDict()
            self.metrics_auroc = nn.ModuleDict()


# ============================================================================
# 4. Training Orchestration
# ============================================================================

def load_pretrained_model(ckpt_path: str, map_location: str = "cpu") -> DeepTAN:
    """Load pretrained DeepTAN model."""
    model_dir = os.path.dirname(ckpt_path)
    hparams_path = os.path.join(model_dir, "version_0", "hparams.yaml")

    load_kwargs = {"map_location": map_location}
    if os.path.exists(hparams_path):
        load_kwargs["hparams_file"] = hparams_path
        logger.info(f"Loading hparams from: {hparams_path}")
    else:
        logger.warning(f"hparams.yaml not found at {hparams_path}; loading without it")

    model = DeepTAN.load_from_checkpoint(ckpt_path, **load_kwargs)
    logger.success(f"Loaded pretrained model from: {ckpt_path}")
    logger.info(f"  input_dim={model.input_dim}, "
                f"output_g_label_dim={model.output_g_label_dim}, "
                f"is_regression={model.is_regression}, "
                f"num_nodes={model.num_all_nodes}")
    return model


def finetune_single_tissue(
    tissue_name: str,
    pretrained_model: DeepTAN,
    datamodule: LightningDataModule,
    cv_weights: torch.Tensor,
    class_weights: Optional[List[float]],
    config: Dict[str, Any],
    tissue_num_classes: Optional[int] = None,
    split_id: Optional[str] = None,
) -> Tuple[str, str, Optional[List[Dict]]]:
    """
    Fine-tune on a single tissue.

    [SPLIT-2] Add split_id support:
      - If specified, outputs are written to output/<tissue>/<split_id>/
      - If None, outputs use the backward-compatible output/<tissue>/finetune_<timestamp>_<rand>/ layout.

    Returns:
        Tuple of (best_checkpoint_path, tissue_log_dir, test_results)
    """
    # [SPLIT-2] Resolve the output directory based on split_id
    if split_id is not None:
        tissue_log_dir = os.path.join(
            config["output_dir"], tissue_name, split_id,
        )
    else:
        tissue_log_dir = os.path.join(
            config["output_dir"], tissue_name,
            f"finetune_{time_string()}_{random_string(5)}",
        )
    os.makedirs(tissue_log_dir, exist_ok=True)

    display_name = f"{tissue_name}/{split_id}" if split_id else tissue_name

    logger.info(f"\n{'='*70}")
    logger.info(f"  FINE-TUNING: {display_name}")
    logger.info(f"  Output: {tissue_log_dir}")
    logger.info(f"  Tissue num_classes: {tissue_num_classes} "
                f"(pretrained: {pretrained_model.output_g_label_dim})")
    logger.info(f"{'='*70}\n")

    pretrained_copy = copy.deepcopy(pretrained_model)

    # Fine-tuning mode: use Xavier initialization for the rebuilt tissue-specific head
    ft_model = DeepTANFineTune(
        pretrained_model=pretrained_copy,
        cv_weights=cv_weights,
        class_weights=class_weights,
        config=config,
        tissue_num_classes=tissue_num_classes,
    )

    assert ft_model.verify_embed_frozen(), "Embed layer is NOT properly frozen!"
    logger.success("✓ Embed layer verified frozen")

    embed_hash_before = _param_hash(ft_model.amsgp.node_embedding_layers.embed)

    # [SPLIT-2] Include split_id in checkpoint filenames for disambiguation
    ckpt_prefix = f"{tissue_name}_{split_id}_" if split_id else f"{tissue_name}_"

    callbacks = [
        EarlyStopping(
            monitor="val/loss_unweighted",
            patience=config["es_patience"],
            mode="min",
            verbose=True,
        ),
        ModelCheckpoint(
            dirpath=tissue_log_dir,
            filename=ckpt_prefix + "epoch={epoch:02d}_val_loss={val/loss_unweighted:.4f}",
            monitor="val/loss_unweighted",
            mode="min",
            save_top_k=3,
            auto_insert_metric_name=False,
        ),
        LearningRateMonitor(logging_interval="epoch"),
    ]

    tb_logger = TensorBoardLogger(save_dir=tissue_log_dir, name="")

    trainer = Trainer(
        enable_progress_bar=True,
        accumulate_grad_batches=config["accumulate_grad_batches"],
        logger=tb_logger,
        log_every_n_steps=5,
        precision=config["precision"],
        accelerator=config["accelerator"],
        devices=config["devices"],
        max_epochs=config["max_epochs"],
        min_epochs=config["min_epochs"],
        callbacks=callbacks,
        num_sanity_val_steps=2,
        default_root_dir=tissue_log_dir,
        gradient_clip_val=config["gradient_clip_val"],
        gradient_clip_algorithm="norm",
    )

    trainer.fit(model=ft_model, datamodule=datamodule)

    embed_hash_after = _param_hash(ft_model.amsgp.node_embedding_layers.embed)
    if embed_hash_before != embed_hash_after:
        logger.error(f"CRITICAL: Embed params changed during training!")
    else:
        logger.success(f"✓ Post-training embed verification passed")

    ckpt_callback = [c for c in callbacks if isinstance(c, ModelCheckpoint)][0]
    best_ckpt = ckpt_callback.best_model_path
    best_score = ckpt_callback.best_model_score

    # Evaluate the best fine-tuned checkpoint on the test set
    test_results = None
    if best_ckpt:
        test_results = trainer.test(
            ckpt_path=best_ckpt, datamodule=datamodule
        )
    else:
        logger.warning("No best checkpoint found; testing with last model")
        test_results = trainer.test(
            model=ft_model, datamodule=datamodule
        )

    logger.success(f"  {display_name} Best val score: {best_score}")
    logger.success(f"  {display_name} Best ckpt: {best_ckpt}")

    metadata = {
        "tissue": tissue_name,
        "split_id": split_id,
        "best_ckpt": best_ckpt,
        "best_val_score": best_score.item() if best_score is not None else None,
        "config": config,
    }
    with open(os.path.join(tissue_log_dir, "finetune_metadata.pkl"), "wb") as f:
        pickle.dump(metadata, f)

    return best_ckpt, tissue_log_dir, test_results


def _param_hash(module: nn.Module) -> str:
    import hashlib
    h = hashlib.md5()
    for p in module.parameters():
        h.update(p.detach().cpu().numpy().tobytes())
    return h.hexdigest()[:16]


# ============================================================================
# 5. Data Module Setup
# ============================================================================

def setup_tissue_datamodule(
    tissue_config: Dict, config: Dict
) -> Tuple[LightningDataModule, Dict[str, int], Optional[int]]:
    """
    Set up LitData-based data module for a single tissue.

    [INT-1] Added pre-flight checks for litdata directory completeness.
    """
    litdata_dir = tissue_config.get("litdata")
    if not litdata_dir:
        raise ValueError("Tissue config must include 'litdata' directory path.")

    if not os.path.isdir(litdata_dir):
        raise FileNotFoundError(
            f"LitData directory does not exist: {litdata_dir}\n"
            f"Please run Run01_build_Tissue_LitData.py first."
        )

    # [INT-1] Pre-flight check: verify LitData subset completeness
    for subset in [const.dkey.abbr_train, const.dkey.abbr_val, const.dkey.abbr_test]:
        subset_dir = os.path.join(litdata_dir, subset)
        if not os.path.isdir(subset_dir):
            raise FileNotFoundError(
                f"LitData subset directory is missing: {subset_dir}\n"
                f"Please confirm that Run01 successfully converted trn/val/tst."
            )
        if len(os.listdir(subset_dir)) == 0:
            raise FileNotFoundError(
                f"LitData subset directory is empty: {subset_dir}\n"
                f"Run01 conversion may not have completed successfully."
            )

    pkl_path = os.path.join(litdata_dir, const.fname.litdata_others2save_pkl)
    if not os.path.exists(pkl_path):
        raise FileNotFoundError(
            f"litdata_others2save.pkl not found at {pkl_path}.\n"
            f"Please confirm that Run01_build_Tissue_LitData.py completed successfully."
        )

    with open(pkl_path, "rb") as f:
        others = pickle.load(f)

    dict_node_names = others["dict_node_names"]
    output_g_label_dim = others["output_g_label_dim"]

    logger.info(f"  LitData: {litdata_dir}")
    logger.info(f"  dict_node_names: {len(dict_node_names)} genes")
    logger.info(f"  output_g_label_dim: {output_g_label_dim}")

    dm = DeepTANDataModuleLit(
        litdata_dir,
        batch_size=config["batch_size"],
        n_workers=config["n_workers"],
    )
    dm.setup()
    return dm, dict_node_names, output_g_label_dim


def load_tissue_class_weights(tissue_config: Dict) -> Optional[List[float]]:
    """
    Load class weights from celltype_onehot parquet.

    [INT-2] Supports fallback: if explicit path not set, look in litdata dir.
    """
    cw_path = tissue_config.get("class_weights_parquet")

    if (not cw_path or not os.path.exists(cw_path)) and tissue_config.get("litdata"):
        fallback_path = os.path.join(
            tissue_config["litdata"], const.fname.label_class_onehot
        )
        if os.path.exists(fallback_path):
            cw_path = fallback_path
            logger.info(f"  class_weights: using {const.fname.label_class_onehot} from the LitData directory")

    if cw_path and os.path.exists(cw_path):
        df = pl.read_parquet(cw_path)
        weights = celltypes_class_weights(df)
        logger.info(f"Loaded class weights ({len(weights)} classes): "
                     f"min={min(weights):.3f}, max={max(weights):.3f}")
        return weights
    logger.warning("No class weights parquet found. Using uniform weights.")
    return None


def _resolve_cv_weights_path(tissue_config: Dict) -> str:
    """
    [INT-3] Resolve CV weights path with fallback to litdata directory.
    """
    cv_path = tissue_config.get("cv_weights", "")
    if cv_path and os.path.exists(cv_path):
        return cv_path

    litdata_dir = tissue_config.get("litdata", "")
    if litdata_dir:
        fallback = os.path.join(litdata_dir, "gene_cv_weights.csv")
        if os.path.exists(fallback):
            logger.info(f"  cv_weights: using gene_cv_weights.csv from the LitData directory")
            return fallback

    return cv_path


# ============================================================================
# 6. Main Entry Point
# ============================================================================

def _process_single_split(
    tissue_name: str,
    split_id: Optional[str],
    split_tissue_cfg: Dict,
    pretrained_model: DeepTAN,
    config: Dict[str, Any],
    lambda_scan: bool,
) -> Optional[str]:
    """
    [SPLIT] Process one data split for one tissue.

    This is separated into its own function to avoid excessive nesting in main().

    Args:
        tissue_name: tissue name
        split_id: split identifier such as "42"; None indicates legacy mode
        split_tissue_cfg: tissue configuration for this split; litdata already points to the concrete subdirectory
        pretrained_model: pretrained model
        config: global configuration
        lambda_scan: whether to run lambda-scan mode

    Returns:
        best_ckpt path, or None
    """
    display_name = f"{tissue_name}/{split_id}" if split_id else tissue_name

    # Setup data
    dm, dict_node_names, output_g_label_dim = setup_tissue_datamodule(
        split_tissue_cfg, config
    )

    pretrained_label_dim = pretrained_model.output_g_label_dim
    if output_g_label_dim != pretrained_label_dim:
        logger.warning(
            f"  ⚠ {display_name}: class-count difference — "
            f"pretrained={pretrained_label_dim}, current_tissue={output_g_label_dim}. "
            f"The GLabelPredictor output layer will be rebuilt automatically."
        )
    else:
        logger.info(f"  ✓ {display_name}: class count is consistent ({output_g_label_dim})")

    # [INT-3] Load CV weights with fallback
    cv_weights_path = _resolve_cv_weights_path(split_tissue_cfg)
    cv_weights = load_cv_weights(cv_weights_path, dict_node_names)

    # [INT-2] Load class weights with fallback
    class_weights = load_tissue_class_weights(split_tissue_cfg)

    # Lambda-scan mode
    if lambda_scan:
        logger.info(f"\n  Lambda scan for {display_name}...")
        for lam in [0.005, 0.01, 0.02, 0.05]:
            scan_cfg = copy.deepcopy(config)
            scan_cfg["lambda_anchor"] = lam
            scan_cfg["max_epochs"] = 5
            scan_cfg["min_epochs"] = 5
            scan_cfg["es_patience"] = 99
            logger.info(f"  λ_anchor = {lam}")
            scan_name = f"{tissue_name}_lambda_{lam}"
            scan_split = f"{split_id}_lambda_{lam}" if split_id else None
            finetune_single_tissue(
                scan_name,
                pretrained_model, dm, cv_weights, class_weights, scan_cfg,
                tissue_num_classes=output_g_label_dim,
                split_id=scan_split,
            )
        return None

    # ── Full fine-tuning ────────────────────────────────────────────────
    best_ckpt, _tissue_log_dir, _test_results = \
        finetune_single_tissue(
            tissue_name, pretrained_model, dm, cv_weights, class_weights,
            config, tissue_num_classes=output_g_label_dim,
            split_id=split_id,
        )

    return best_ckpt


def main():

    logger.info(f"DeepTAN module path: {const.__file__}")
    parser = argparse.ArgumentParser(
        description="Run02: tissue-specific DeepTAN fine-tuning from a Run01 LitData directory."
    )
    parser.add_argument("--config", type=str, default=None,
                        help="Path to Run02 tissue fine-tuning YAML config.")
    parser.add_argument("--tissue", type=str, default=None,
                        help="Fine-tune only this tissue/run name. Default: all entries in config.tissue_order.")
    parser.add_argument("--split", type=str, default=None,
                        help="Optional split identifier for legacy multi-split LitData directories. Not needed for standard single-run use.")
    parser.add_argument("--lambda_scan", action="store_true",
                        help="Run lambda_anchor quick scan (5 epochs each)")
    args = parser.parse_args()

    config = load_config(args.config)

    ltn.seed_everything(config["seed"], workers=True)
    logger.info(f"Random seed: {config['seed']}")

    map_loc = get_map_location()
    logger.info(f"Map location: {map_loc}")

    pretrained_model = load_pretrained_model(config["pretrained_ckpt"], map_loc)


    tissue_names = [args.tissue] if args.tissue else config["tissue_order"]
    logger.info(f"Training order: {tissue_names}")

    results = {}
    for tissue_name in tissue_names:
        if tissue_name not in config["tissues"]:
            logger.error(f"Tissue '{tissue_name}' not in config. Skipping.")
            continue

        tissue_cfg = config["tissues"][tissue_name]
        litdata_base = tissue_cfg.get("litdata", "")

        # ── [SPLIT-1] Automatically discover split subdirectories ───────
        splits = _discover_splits(litdata_base)

        if splits:
            # ── Multi-split mode ─────────────────────────────────────
            # Filter: if --split is specified, run only that split
            if args.split:
                if args.split not in splits:
                    logger.error(
                        f"  specified split {args.split!r} is not among the discovered splits: {splits}"
                    )
                    continue
                splits = [args.split]

            logger.info(
                f"\n  [SPLIT] {tissue_name}: discovered {len(splits)} data splits: {splits}"
            )

            for split_id in splits:
                split_litdata = os.path.join(litdata_base, split_id)

                # Build a copy of tissue_cfg for this split; litdata points to the concrete subdirectory
                split_tissue_cfg = copy.deepcopy(tissue_cfg)
                split_tissue_cfg["litdata"] = split_litdata

                logger.info(f"\n{'─'*70}")
                logger.info(f"  [{tissue_name}] Split {split_id} — litdata: {split_litdata}")
                logger.info(f"{'─'*70}")

                best_ckpt = _process_single_split(
                    tissue_name=tissue_name,
                    split_id=split_id,
                    split_tissue_cfg=split_tissue_cfg,
                    pretrained_model=pretrained_model,
                    config=config,
                    lambda_scan=args.lambda_scan,
                )

                result_key = f"{tissue_name}/{split_id}"
                if best_ckpt:
                    results[result_key] = best_ckpt
        else:
            # ── Legacy mode: the LitData directory itself is valid; no child split directories ──
            if args.split:
                logger.warning(
                    f"  --split {args.split} was specified, but no split subdirectory was found under {litdata_base}; "
                    f"running in single-split mode."
                )

            logger.info(f"\n  [SPLIT] {tissue_name}: single-split mode (using the LitData directory directly)")

            best_ckpt = _process_single_split(
                tissue_name=tissue_name,
                split_id=None,
                split_tissue_cfg=tissue_cfg,
                pretrained_model=pretrained_model,
                config=config,
                lambda_scan=args.lambda_scan,
            )

            if best_ckpt:
                results[tissue_name] = best_ckpt

    # ── Summary ─────────────────────────────────────────────────────────
    logger.info("\n" + "=" * 70)
    logger.info("  FINE-TUNING COMPLETE")
    logger.info("=" * 70)
    for key, ckpt in results.items():
        logger.info(f"  {key}: {ckpt}")

    summary_path = os.path.join(config["output_dir"], "finetune_summary.pkl")
    os.makedirs(os.path.dirname(summary_path), exist_ok=True)
    with open(summary_path, "wb") as f:
        pickle.dump(results, f)
    logger.success(f"Summary saved to {summary_path}")



if __name__ == "__main__":
    main()
