#!/usr/bin/env bash
# ==============================================================================
# Run02: Tissue-Specific DeepTAN Fine-Tuning
# ==============================================================================
#
# Purpose:
#   Fine-tune an scRNA-pretrained DeepTAN model using the tissue LitData
#   generated by Run01.
#
# Pipeline position:
#   Run01: user-defined tissue scRNA files -> LitData
#   Run02: LitData -> tissue-specific fine-tuned DeepTAN checkpoint
#   Run03: LitData + checkpoint -> tissue-specific latent network
#
# Usage:
#   1. Edit Section 1 paths, or pass a config file as the first argument.
#
#   2. Make this script executable:
#        chmod +x scripts/Run02_Tissue_finetune.sh
#
#   3. Run:
#        bash scripts/Run02_Tissue_finetune.sh configs/Run02_Tissue_finetune.yaml
#
# Optional arguments after the config path are forwarded to Python:
#        bash scripts/Run02_Tissue_finetune.sh configs/Run02_Tissue_finetune.yaml --skip_tsa
#        bash scripts/Run02_Tissue_finetune.sh configs/Run02_Tissue_finetune.yaml --tissue ExampleTissue
# ==============================================================================

set -euo pipefail


# ------------------------------------------------------------------------------
# 0. Optional: activate conda / mamba environment
# ------------------------------------------------------------------------------
# source ~/miniconda3/etc/profile.d/conda.sh
# conda activate your_deeptan_env_name


# ==============================================================================
# 1. User-configurable paths
# ==============================================================================

# Local DeepTAN source checkout. Leave empty if DeepTAN is already installed in
# the active Python environment.
DEEPTAN_SRC="/path/to/deeptan-dev/src"

# Run02 Python script.
RUN02_SCRIPT="/path/to/Tissue_DeepTAN_finetune/src/Run02_Tissue_finetune.py"

# Default config file. It can be overridden by passing a config path as $1.
DEFAULT_CONFIG_FILE="/path/to/Tissue_DeepTAN_finetune/configs/Run02_Tissue_finetune.yaml"


# ==============================================================================
# 2. Parse arguments
# ==============================================================================

CONFIG_FILE="${1:-${DEFAULT_CONFIG_FILE}}"

if [[ $# -gt 0 ]]; then
  shift
fi

EXTRA_ARGS=("$@")


# ==============================================================================
# 3. Logging
# ==============================================================================

LOG_DIR="${LOG_DIR:-logs/run02_tissue_finetune}"
mkdir -p "${LOG_DIR}"
LOG_FILE="${LOG_DIR}/run02_tissue_finetune_$(date +%Y%m%d_%H%M%S).log"


# ==============================================================================
# 4. Sanity checks
# ==============================================================================

check_file_exists() {
  local file_path="$1"
  local description="$2"

  if [[ ! -f "${file_path}" ]]; then
    echo "[ERROR] Missing ${description}: ${file_path}" >&2
    exit 1
  fi
}

check_file_exists "${RUN02_SCRIPT}" "Run02 Python script"
check_file_exists "${CONFIG_FILE}" "Run02 YAML config"

if [[ -n "${DEEPTAN_SRC}" ]]; then
  if [[ ! -d "${DEEPTAN_SRC}" ]]; then
    echo "[ERROR] DEEPTAN_SRC does not exist: ${DEEPTAN_SRC}" >&2
    exit 1
  fi
  export DEEPTAN_SRC
fi


# ==============================================================================
# 5. Print run information
# ==============================================================================

echo "=============================================================================="
echo "Run02 | Tissue-Specific DeepTAN Fine-Tuning"
echo "Python        : $(which python)"
echo "RUN02_SCRIPT  : ${RUN02_SCRIPT}"
echo "CONFIG_FILE   : ${CONFIG_FILE}"
echo "DEEPTAN_SRC   : ${DEEPTAN_SRC:-<use environment package>}"
echo "LOG_FILE      : ${LOG_FILE}"
echo "EXTRA_ARGS    : ${EXTRA_ARGS[*]:-<none>}"
echo "=============================================================================="
echo


# ==============================================================================
# 6. Run fine-tuning
# ==============================================================================

python -u "${RUN02_SCRIPT}" \
  --config "${CONFIG_FILE}" \
  "${EXTRA_ARGS[@]}" \
  2>&1 | tee "${LOG_FILE}"


echo
echo "=============================================================================="
echo "Run02 finished."
echo "Check output_dir in:"
echo "  ${CONFIG_FILE}"
echo "=============================================================================="
