#!/usr/bin/env bash
# ==============================================================================
# Run Trait-aware Bulk Network Downstream Analysis
#
# Purpose:
#   Run downstream module/hub/gene-set analysis on the trait-aware bulk network
#   extracted by Run03.
#
# Pipeline position:
#   Run01: raw bulk files -> LitData
#   Run02: LitData -> fine-tuned BulkExpand-DeepTAN checkpoint
#   Run03: LitData + checkpoint -> trait-aware network
#   Run04: trait-aware network -> downstream module/hub/gene-set analysis
#   Run05: downstream analysis -> network figure
#
# Usage:
#   1. Edit the paths in Section 1.
#
#   2. Make this script executable:
#        chmod +x 04_run_downstream_analysis.sh
#
#   3. Run:
#        bash 04_run_downstream_analysis.sh
#      or:
#        ./04_run_downstream_analysis.sh
#
# Notes:
#   - NETWORK_DIR should point to the Run03 trait_network directory.
#   - NETWORK_DIR must contain:
#        bulk_trait_edge_table.parquet
#
#   - RANDOM_SEED is only used for reproducible community detection.
#     It is NOT a data split seed and does NOT choose a LitData folder.
# ==============================================================================

set -euo pipefail


# ------------------------------------------------------------------------------
# 0. Optional: activate conda / mamba environment
# ------------------------------------------------------------------------------
# If you already activated the correct environment, keep these lines commented.
# Otherwise, uncomment and edit the environment name.
#
# source ~/miniconda3/etc/profile.d/conda.sh
# conda activate your_deeptan_env_name


# ==============================================================================
# 1. User-configurable paths
# ==============================================================================

# Downstream analysis Python script.
# This script should be the optimized user-friendly version generated earlier.
PY_SCRIPT="/path/to/bulk_network_downstream_analysis_userfriendly.py"

# Directory generated by Run03 network extraction.
# It should contain:
#   bulk_trait_edge_table.parquet
NETWORK_DIR="/path/to/network_output/trait_network"

# Output directory for downstream analysis results.
# This script will create:
#   ${OUT_DIR}/tables/
#   ${OUT_DIR}/gene_sets/
OUT_DIR="/path/to/downstream_output"


# ==============================================================================
# 2. Analysis parameters
# ==============================================================================

# Random seed for reproducible community detection.
# This is NOT a data split seed.
RANDOM_SEED=42

# Signed edge-weight column from bulk_trait_edge_table.parquet.
# The analysis uses abs(${WEIGHT_COL}) as non-negative edge strength.
# Common choices:
#   w_ft     : fine-tuned latent edge weight
#   delta_w  : trait-aware change relative to expanded-pretrained baseline
WEIGHT_COL="w_ft"

# Fraction of strongest edges used for module detection.
# 1.0 means all non-zero edges after optional min_abs_weight filtering.
MODULE_TOP_FRAC=1.0

# Optional minimum absolute edge strength.
# Leave empty to disable this threshold.
# Example:
#   MIN_ABS_WEIGHT="0.10"
MIN_ABS_WEIGHT=""

# Raw communities smaller than this size are merged into the largest retained module.
MIN_MODULE_SIZE=50

# Community detection resolution for Leiden/Louvain when available.
RESOLUTION=1.3

# Hub definition within each module.
HUB_TOP_FRAC=0.10
MIN_HUBS=1
MAX_HUBS=100000


# ==============================================================================
# 3. Logging
# ==============================================================================

LOG_DIR="${OUT_DIR}/logs"
mkdir -p "${LOG_DIR}"

LOG_FILE="${LOG_DIR}/downstream_analysis_$(date +%Y%m%d_%H%M%S).log"


# ==============================================================================
# 4. Sanity checks
# ==============================================================================

check_file_exists() {
  local file_path="$1"
  local description="$2"

  if [[ ! -f "${file_path}" ]]; then
    echo "[ERROR] Missing ${description}: ${file_path}" >&2
    exit 1
  fi
}

check_dir_exists() {
  local dir_path="$1"
  local description="$2"

  if [[ ! -d "${dir_path}" ]]; then
    echo "[ERROR] Missing ${description}: ${dir_path}" >&2
    exit 1
  fi
}

check_file_exists "${PY_SCRIPT}" "downstream analysis Python script"
check_dir_exists "${NETWORK_DIR}" "Run03 trait network directory"
check_file_exists "${NETWORK_DIR}/bulk_trait_edge_table.parquet" "trait network edge table"

mkdir -p "${OUT_DIR}"


# ==============================================================================
# 5. Print run information
# ==============================================================================

echo "=============================================================================="
echo "Trait-aware Bulk Network Downstream Analysis"
echo "Python          : $(which python)"
echo "PY_SCRIPT       : ${PY_SCRIPT}"
echo "NETWORK_DIR     : ${NETWORK_DIR}"
echo "OUT_DIR         : ${OUT_DIR}"
echo "RANDOM_SEED     : ${RANDOM_SEED}"
echo "WEIGHT_COL      : ${WEIGHT_COL}"
echo "MODULE_TOP_FRAC : ${MODULE_TOP_FRAC}"
echo "MIN_ABS_WEIGHT  : ${MIN_ABS_WEIGHT:-<disabled>}"
echo "MIN_MODULE_SIZE : ${MIN_MODULE_SIZE}"
echo "RESOLUTION      : ${RESOLUTION}"
echo "HUB_TOP_FRAC    : ${HUB_TOP_FRAC}"
echo "LOG_FILE        : ${LOG_FILE}"
echo "=============================================================================="
echo


# ==============================================================================
# 6. Run downstream analysis
# ==============================================================================

CMD=(
  python -u "${PY_SCRIPT}"
  --network_dir "${NETWORK_DIR}"
  --out_dir "${OUT_DIR}"
  --seed "${RANDOM_SEED}"
  --weight_col "${WEIGHT_COL}"
  --module_top_frac "${MODULE_TOP_FRAC}"
  --min_module_size "${MIN_MODULE_SIZE}"
  --resolution "${RESOLUTION}"
  --hub_top_frac "${HUB_TOP_FRAC}"
  --min_hubs "${MIN_HUBS}"
  --max_hubs "${MAX_HUBS}"
)

# Add optional minimum absolute edge threshold only when it is explicitly set.
if [[ -n "${MIN_ABS_WEIGHT}" ]]; then
  CMD+=(--min_abs_weight "${MIN_ABS_WEIGHT}")
fi

"${CMD[@]}" 2>&1 | tee "${LOG_FILE}"


# ==============================================================================
# 7. Finish
# ==============================================================================

echo
echo "=============================================================================="
echo "Downstream analysis finished."
echo "Output directory:"
echo "  ${OUT_DIR}"
echo
echo "Expected outputs:"
echo "  ${OUT_DIR}/tables/analysis_edge_table.parquet"
echo "  ${OUT_DIR}/tables/analysis_metadata.yaml"
echo "  ${OUT_DIR}/tables/module_assignment.csv"
echo "  ${OUT_DIR}/tables/module_summary.csv"
echo "  ${OUT_DIR}/tables/module_count_summary.csv"
echo "  ${OUT_DIR}/tables/hub_gene_summary.csv"
echo "  ${OUT_DIR}/tables/module_edges.parquet"
echo "  ${OUT_DIR}/gene_sets/module_genes/"
echo "  ${OUT_DIR}/gene_sets/module_hubs/"
echo
echo "Log file:"
echo "  ${LOG_FILE}"
echo "=============================================================================="
