python run_sc.py 01
python run_sc.py 02
python run_sc.py 03
python run_sc.py 04
python run_sc.py 05
python run_sc.py 06
python run_sc.py 07
python run_sc.py 08
python run_sc.py 09
python run_sc.py 10
