#!/usr/bin/env bash
# ==============================================================================
# Run02: Cell-Type DeepTAN Fine-Tuning
# ==============================================================================
# Purpose:
#   Fine-tune a scRNA-pretrained DeepTAN model using the LitData generated by
#   Run01.
#
# Pipeline position:
#   Run01: user-defined scRNA files -> LitData
#   Run02: LitData -> cell-type fine-tuned DeepTAN checkpoint
#   Run03: LitData + checkpoint -> cell-specific network
#
# Usage:
#   bash 02_finetune_cell.sh configs/cell_finetune_single.yaml
#
# Optional extra arguments are passed directly to the Python script:
#   bash 02_finetune_cell.sh configs/cell_finetune_single.yaml --skip_tsa
#   bash 02_finetune_cell.sh configs/cell_finetune_single.yaml --tissue ExampleCellType
#   bash 02_finetune_cell.sh configs/cell_finetune_single.yaml --tissue ExampleCellType --split 42
#
# Notes:
#   - In the single-run GitHub workflow, the LitData directory in the YAML should
#     point directly to the Run01 output directory.
#   - The YAML field seed is a training reproducibility seed, not a data split ID.
# ============================================================================== 

set -euo pipefail


# ------------------------------------------------------------------------------
# 0. Optional: activate conda / mamba environment
# ------------------------------------------------------------------------------
# source ~/miniconda3/etc/profile.d/conda.sh
# conda activate your_deeptan_env_name


# ==============================================================================
# 1. User-configurable paths
# ===============================================================================

# Local DeepTAN source checkout. Leave empty if DeepTAN is already installed in
# the active Python environment.
DEEPTAN_SRC="/path/to/deeptan-dev/src"

# Run02 Python script.
RUN02_SCRIPT="/path/to/run_02_cell_finetune_userfriendly.py"

# Config file. The first command-line argument overrides this default.
DEFAULT_CONFIG_FILE="/path/to/cell_finetune_single.yaml"


# ==============================================================================
# 2. Runtime options
# ===============================================================================

# Optional GPU selection. Leave empty to use the environment default.
CUDA_DEVICE="0"

CONFIG_FILE="${1:-${DEFAULT_CONFIG_FILE}}"
if [[ $# -gt 0 ]]; then
  shift
fi
EXTRA_ARGS=("$@")


# ==============================================================================
# 3. Logging
# ===============================================================================

LOG_ROOT="${LOG_ROOT:-logs/run02_cell_finetune}"
mkdir -p "${LOG_ROOT}"
LOG_FILE="${LOG_ROOT}/cell_finetune_$(date +%Y%m%d_%H%M%S).log"


# ==============================================================================
# 4. Sanity checks
# ===============================================================================

check_file_exists() {
  local file_path="$1"
  local description="$2"

  if [[ ! -f "${file_path}" ]]; then
    echo "[ERROR] Missing ${description}: ${file_path}" >&2
    exit 1
  fi
}

check_file_exists "${RUN02_SCRIPT}" "Run02 Python script"
check_file_exists "${CONFIG_FILE}" "Run02 YAML config"

if [[ -n "${DEEPTAN_SRC}" ]]; then
  if [[ ! -d "${DEEPTAN_SRC}" ]]; then
    echo "[ERROR] DEEPTAN_SRC does not exist: ${DEEPTAN_SRC}" >&2
    exit 1
  fi
  export DEEPTAN_SRC
fi

if [[ -n "${CUDA_DEVICE}" ]]; then
  export CUDA_VISIBLE_DEVICES="${CUDA_DEVICE}"
fi


# ==============================================================================
# 5. Print run information
# ===============================================================================

echo "=============================================================================="
echo "Run02 | Cell-Type DeepTAN Fine-Tuning"
echo "Python          : $(which python)"
echo "RUN02_SCRIPT    : ${RUN02_SCRIPT}"
echo "CONFIG_FILE     : ${CONFIG_FILE}"
echo "DEEPTAN_SRC     : ${DEEPTAN_SRC:-<use environment package>}"
echo "CUDA_VISIBLE_DEVICES : ${CUDA_VISIBLE_DEVICES:-<not set>}"
echo "EXTRA_ARGS      : ${EXTRA_ARGS[*]:-<none>}"
echo "LOG_FILE        : ${LOG_FILE}"
echo "=============================================================================="
echo


# ==============================================================================
# 6. Run fine-tuning
# ===============================================================================

python -u "${RUN02_SCRIPT}" \
  --config "${CONFIG_FILE}" \
  "${EXTRA_ARGS[@]}" \
  2>&1 | tee "${LOG_FILE}"


echo
echo "=============================================================================="
echo "Run02 finished."
echo "Config file: ${CONFIG_FILE}"
echo "Log file   : ${LOG_FILE}"
echo "=============================================================================="
